<?php

/**
 * @file
 * This module implements SBSYS ESDH backend for use in os2web
 */

define('MM_IMPORT_DIR', 'public://edoc_middelfart');
define('MM_DEFAULT_APPROVED', 'Hennys testudvalg');
define('MM_DEFAULT_BANNED_CHAR', '&#xC;');
define('MM_DEFAULT_BANNED_REGEX', '/&#x.*;/');

/**
 * Implements hook_ctools_plugin_directory().
 *
 * Register as provider of esdh plugins
 */
function os2web_edoc_middelfart_esdh_ctools_plugin_directory($module, $plugin) {
  if ($module == 'os2web_esdh_provider') {
    return "plugins/$plugin";
  }
}

/**
 * Implements hook_form_alter().
 *
 * Add configuration to the settings form.
 */
function os2web_edoc_middelfart_esdh_form_os2web_settings_settings_form_alter(&$form, &$form_state) {
  // MM configuration.
  $form['meetings'] = array(
    '#type' => 'fieldset',
    '#title' => 'Referat import',
    '#description' => 'Indstillinger der vedrører importen af eDoc referater og dagsordener.',
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
  $form['meetings']['os2web_edoc_middelfart_esdh_mm_path'] = array(
    '#type' => 'textfield',
    '#title' => 'Sti til edoc publish folder.',
    '#description' => 'Dette er stien hvor ESDH publisere .XML filer til.',
    '#default_value' => variable_get('os2web_edoc_middelfart_esdh_mm_path', MM_IMPORT_DIR),
  );
  $form['meetings']['os2web_edoc_middelfart_esdh_mm_is_abs'] = array(
    '#type' => 'checkbox',
    '#title' => t('Is import path an absolute path'),
    '#description' => t('Mark this checkbox if you import path is a absolute and not relative (e.g. public://) path'),
    '#default_value' => variable_get('os2web_edoc_middelfart_esdh_mm_is_abs', FALSE),
  );
  $form['meetings']['os2web_edoc_middelfart_esdh_mm_abs_path_subs'] = array(
    '#type' => 'textfield',
    '#title' => t('Substution for the absolute path'),
    '#description' => t('Which part of the absolute path should be substitued with the <i>public://</i> suffix. <br/> <b>NOTE</b> trailing slash is required !!! <br/>
    To use this functionality a symlink has to be created in <i>sites/default/files</i>, which would lead to absolute path.<br/>
    <br/>
    <b>Example: </b><br/>
    symlink = <i>sites/default/files/edoc_copy</i><br/>
    absolute path = <i>/var/wwwn/ballerup_edoc/edoc_copy</i> <br/>
    substituion part = <i>/var/wwwn/ballerup_edoc/</i>'),
    '#default_value' => variable_get('os2web_edoc_middelfart_esdh_mm_abs_path_subs'),
    '#states' => array(
      'invisible' => array(
        ':input[name="os2web_edoc_middelfart_esdh_mm_is_abs"]' => array('checked' => FALSE),
      ),
    ),
  );
  $form['meetings']['os2web_edoc_middelfart_esdh_approved_committees'] = array(
    '#type' => 'textarea',
    '#title' => 'Godkendte Udvalg',
    '#description' => 'Komma sepereret liste over udvalgs-id der er godkendt til publisering.',
    '#default_value' => variable_get('os2web_edoc_middelfart_esdh_approved_committees', MM_DEFAULT_APPROVED),
  );
  $form['meetings']['os2web_edoc_middelfart_esdh_import_closed_agenda'] = array(
    '#type' => 'checkbox',
    '#title' => 'Import closed agenda',
    '#maxlength' => 200,
    '#description' => t('This decides if the closed agenda bullet points\' content will be imported.'),
    '#default_value' => variable_get('os2web_edoc_middelfart_esdh_import_closed_agenda',FALSE)
  );
  $form['meetings']['os2web_edoc_middelfart_esdh_banned_activate_regex'] = array(
    '#type' => 'checkbox',
    '#title' => 'Aktiver regex',
    '#description' => t('This decides whether the regulax expression or CSV list will be used to trim out the unneeded content from XMLs.'),
    '#default_value' => variable_get('os2web_edoc_middelfart_esdh_banned_activate_regex', FALSE),
  );

  $form['meetings']['os2web_edoc_middelfart_esdh_banned_special_char'] = array(
    '#type' => 'textfield',
    '#title' => 'Ikke standard XML tegn der skal fjernes ved import (CSV)',
    '#maxlength' => 200,
    '#description' => 'Komma sepereret liste over ikke standard tegn der skal fjernes ved import.',
    '#default_value' => variable_get('os2web_edoc_middelfart_esdh_banned_special_char', MM_DEFAULT_BANNED_CHAR),
    '#states' => array(
      'invisible' => array(
        ':input[name="os2web_edoc_middelfart_esdh_banned_activate_regex"]' => array('checked' => TRUE),
      ),
    ),
  );
  $form['meetings']['os2web_edoc_middelfart_esdh_banned_special_regex'] = array(
    '#type' => 'textfield',
    '#title' => 'Ikke standard XML tegn der skal fjernes ved import (regex)',
    '#maxlength' => 200,
    '#description' => 'Regular expression over ikke standard tegn der skal fjernes ved import.',
    '#default_value' => variable_get('os2web_edoc_middelfart_esdh_banned_special_regex', MM_DEFAULT_BANNED_REGEX),
    '#states' => array(
      'invisible' => array(
        ':input[name="os2web_edoc_middelfart_esdh_banned_activate_regex"]' => array('checked' => FALSE),
      ),
    ),
  );
  $form['meetings']['os2web_edoc_middelfart_esdh_nl2br'] = array(
    '#type' => 'checkbox',
    '#title' => 'Omskriv linjeskift til html breaks',
    '#description' => 'Hvis indholdet er uformatteret tekst vil systemet ikke håndtere linjeskift medmindre denne funktion er slået til.',
    '#default_value' => variable_get('os2web_edoc_middelfart_esdh_nl2br', TRUE),
  );
  $form['meetings']['os2web_edoc_middelfart_esdh_bullet_source'] = array(
    '#type' => 'radios',
    '#title' => 'Source of bullet content',
    '#options' => array('xml' => t('Use XML'), 'pdf' => t('Use PDF')),
    '#description' => 'This decides whether the bullet information will be imported from XML or PDF files.<br/>
		      Please note, that if PDF option is used server should have <b>pdf2htmlEX</b> installed and <b>os2dagsorden_pdf2htmlex</b> module activated. ',
    '#default_value' => variable_get('os2web_edoc_middelfart_esdh_bullet_source', 'xml'),
  );
  $form['meetings']['os2web_edoc_middelfart_esdh_empty_bullet_title'] = array(
    '#type' => 'textfield',
    '#title' => ' Title for bullet points imported from PDF files',
    '#maxlength' => 200,
    '#description' => 'This will be used as bullet point title for bullet points imported from PDF files',
    '#default_value' => variable_get('os2web_edoc_middelfart_esdh_empty_bullet_title','Indhold')
  );
}

/**
 * Implements hook_os2web_help().
 */
function os2web_edoc_middelfart_esdh_os2web_help($sections) {

  // Content types.
  $sections['contenttype'] .= t('<p><b>Meeting node:</b> Add <a href="@url" target="_blank">meetings</a> directly.<br /><i><a href="@edoc" target="_blank">See the advanced documentation for the OS2web eDoc module</a>(.pdf)</i></p>', array('@url' => url('node/add/os2web_meetings_meeting'), '@edoc' => file_create_url(drupal_get_path('module', 'os2web_edoc_middelfart_esdh') . '/os2web_edoc_modul_setup.pdf')));
  $sections['import'] .= t('<p><b>Import agenades:</b> <a href="@edoc" target="_blank">See the advanced documentation for the OS2web eDoc module import</a>(.pdf)</i></p>', array('@url' => url('node/add/os2web_meetings_meeting'), '@edoc' => file_create_url(drupal_get_path('module', 'os2web_edoc_middelfart_esdh') . '/os2web_edoc_modul_setup.pdf')));
  $sections['documentation'] .= t('<p><b>PDF documentation for edoc:</b> <a href="@edoc" target="_blank">Documentation for the OS2web eDoc module</a>(.pdf)</i></p>', array('@url' => url('node/add/os2web_meetings_meeting'), '@edoc' => file_create_url(drupal_get_path('module', 'os2web_edoc_middelfart_esdh') . '/os2web_edoc_modul_setup.pdf')));
  return $sections;

}



/**
 * Implements hook_help().
 */
function os2web_edoc_middelfart_esdh_help($path, $arg) {
  switch ($path) {
    case 'admin/help#os2web_edoc_middelfart_esdh':
      return t('Se the OS2web documentation under "help" for details. If you don not have that please activate the OS2web Help module');
  }
}
