<?php
/**
* os2dagsorden_settings
*
* PHP version 5
*
* @category OS2dagsorden
* @package  OS2dagsorden_Importer
* @file     Code for the OS2dagsorden settings feature.
* @author   Stanislav Kutasevits <stan@bellcom.dk>
* @license  http://www.gnu.org/licenses/gpl-2.0.html GNU General Public License, version 2
* @link     http://bellcom.dk
*/

//include_once('os2dagsorden_settings.features.inc');

/**
 * Implementation of hook_menu()
 *
 * @return list of links
 */
function os2dagsorden_settings_menu() {
    $items['admin/config/os2dagsorden'] = array(
        'title' => 'OS2dagsorden Setup',
        'description' => 'Set up OS2 cms services',
        'position' => 'right',
        'weight' => -15,
        'access arguments' => array('administer os2web'),
        'page callback' => 'system_admin_menu_block_page',
        'file' => 'system.admin.inc',
        'file path' => drupal_get_path('module', 'system'),
        'type' => MENU_NORMAL_ITEM,
    );
    $items['admin/config/os2dagsorden/settings'] = array(
        'title' => 'OS2dagsorden Settings',
        'description' => 'General settings for the OS2dagsorden project',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('os2dagsorden_settings_settings_form'),
        'access arguments' => array('administer os2web'),
        'type' => MENU_NORMAL_ITEM,
        'file' => 'os2dagsorden_settings.admin.inc',
    );
    $items['admin/config/os2dagsorden/flush_calendar_preferences'] = array(
        'title' => 'Calendar preferences flushing',
        'description' => 'Clicking on this link all the calendar preferences (pol/org) will be flushed. The preferences are retrieved again from SOFD, once "Importer cron" is run',
        'page callback' => 'os2dagsorden_settings_flush_calendar_preferences',
        'access arguments' => array('administer os2web'),
        'type' => MENU_NORMAL_ITEM,
    );
    $items['get_committee/autocomplete'] = array(
       'page callback' => 'os2dagsorden_settings_committee_autocomplete_callback',
      'page arguments' => array(2),
      'access arguments' => array('use autocomplete'),
    'type' => MENU_CALLBACK,  
    );

    $items['os2dagsorden/export_settings'] = array(
        'page callback' => 'os2dagsorden_settings_export_to_file',
        'access arguments' => array('administer os2web'),
        'type' => MENU_CALLBACK,
    );
    
    return $items;
}

function os2dagsorden_settings_export_to_file(){
    header("Content-type: text/plain");
    header("Content-Disposition: attachment; filename=os2dagsorden_settings.settings");

    $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_show_meeting_committee'] = variable_get('os2dagsorden_show_meeting_committee', TRUE);
    $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_show_meeting_enddate'] = variable_get('os2dagsorden_show_meeting_enddate', TRUE);
    $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_show_meeting_type'] = variable_get('os2dagsorden_show_meeting_type', TRUE);
    $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_show_samlet_dokument_link'] =variable_get('os2dagsorden_show_samlet_dokument_link', TRUE);
    $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_show_participants_afbud'] = variable_get('os2dagsorden_show_participants_afbud', FALSE);
    $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_show_print_icon'] = variable_get('os2dagsorden_show_print_icon', FALSE);
    $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_show_comments'] = variable_get('os2dagsorden_show_comments', FALSE);
    $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_show_closed_bullet_point_content'] = variable_get('os2dagsorden_show_closed_bullet_point_content', FALSE);
    $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_show_bilag'] = variable_get('os2dagsorden_show_bilag', TRUE);
    $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_sager_group_title'] = variable_get('os2dagsorden_sager_group_title', 'Sager');
    $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_group_closed_bullet_points'] = variable_get('os2dagsorden_group_closed_bullet_points', 'false');
    $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_hidden_agenda_committee'] = variable_get('os2dagsorden_hidden_agenda_committee', OS2DAGSORDEN_HIDDEN_AGENGA_COMMITTEE);
    $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_meeting_description_download_title'] = variable_get('os2dagsorden_meeting_description_download_title', 'Hent samlet dokument i PDF');
    $setting_array['os2dagsorden_meeting_view_settings']['os2dagsorden_meeting_description_download_title_additional'] = variable_get('os2dagsorden_meeting_description_download_title_additional', 'Hent tillægsdokument i PDF');

    $setting_array['os2dagsorden_speaker_paper_settings']['os2dagsorden_shared_speaker_paper'] = variable_get('os2dagsorden_shared_speaker_paper', TRUE);

    $setting_array['os2dagsorden_meeting_view_layout']['os2dagsorden_expand_all_bullets'] = variable_get('os2dagsorden_expand_all_bullets',FALSE);
    $setting_array['os2dagsorden_meeting_view_layout']['os2dagsorden_expand_attachment_onload'] = variable_get('os2dagsorden_expand_attachment_onload', FALSE);
    $setting_array['os2dagsorden_meeting_view_layout']['os2dagsorden_expand_bilags'] = variable_get('os2dagsorden_expand_bilags', 'true');
    $setting_array['os2dagsorden_meeting_view_layout']['os2dagsorden_expand_cases'] = variable_get('os2dagsorden_expand_cases', 'false');
    $setting_array['os2dagsorden_meeting_view_layout']['os2dagsorden_show_massive_expand_collapse_button'] = variable_get('os2dagsorden_show_massive_expand_collapse_button', 'true');
    $setting_array['os2dagsorden_meeting_view_layout']['os2dagsorden_show_bilag_bullet_point'] = variable_get('os2dagsorden_show_bilag_bullet_point', FALSE);
    $setting_array['os2dagsorden_meeting_view_layout']['os2dagsorden_show_case_bullet_point'] = variable_get('os2dagsorden_show_case_bullet_point', FALSE);

    $setting_array['os2dagsorden_latest_meetings_view_settings']['os2dagsorden_latest_meetings_view_mode'] = variable_get('os2dagsorden_latest_meetings_view_mode', 'all');
    $setting_array['os2dagsorden_latest_meetings_view_settings']['os2dagsorden_meetings_views_last_8_show_meeting_committee'] = variable_get('os2dagsorden_meetings_views_last_8_show_meeting_committee', TRUE);
    $setting_array['os2dagsorden_latest_meetings_view_settings']['os2dagsorden_meetings_views_last_8_show_meeting_location'] = variable_get('os2dagsorden_meetings_views_last_8_show_meeting_location', TRUE);

    $setting_array['os2dagsorden_frontpage_layout']['os2dagsorden_collapse_menu'] = variable_get('os2dagsorden_collapse_menu', TRUE);
    $setting_array['os2dagsorden_frontpage_layout']['os2dagsorden_show_search_block_title'] = variable_get('os2dagsorden_show_search_block_title', 'true');
 
    $setting_array['os2dagsorden_meeting_search_view_settings']['os2dagsorden_meetings_search_show_meeting_committee'] = variable_get('os2dagsorden_meetings_search_show_meeting_committee', TRUE);
    $setting_array['os2dagsorden_meeting_search_view_settings']['os2dagsorden_meetings_search_show_meeting_status'] = variable_get('os2dagsorden_meetings_search_show_meeting_status', FALSE);
    $setting_array['os2dagsorden_meeting_search_view_settings']['os2dagsorden_search_startdate'] = variable_get('os2dagsorden_search_startdate', 1);
    $setting_array['os2dagsorden_meeting_search_view_settings']['os2dagsorden_search_enddate'] = variable_get('os2dagsorden_search_enddate', 1);
  
    $setting_array['os2dagsorden_sidepane_menu_layout']['os2dagsorden_budget_committee'] = variable_get('os2dagsorden_budget_committee', FALSE);

    $setting_array['os2dagsorden_meeting_import']['os2dagsorden_participants_delimeter'] = variable_get('os2dagsorden_participants_delimeter', ', ');
    $setting_array['os2dagsorden_meeting_import']['os2dagsorden_send_notification_committee'] = variable_get('os2dagsorden_send_notification_committee', FALSE);
    $setting_array['os2dagsorden_meeting_import']['os2dagsorden_send_email_subject'] = variable_get('os2dagsorden_send_email_subject', '!meeting_type til !committee er publiceret');
    $setting_array['os2dagsorden_meeting_import']['os2dagsorden_send_email_body'] = variable_get('os2dagsorden_send_email_body', 'Til !user' . PHP_EOL . PHP_EOL .
      'Du abonnerer på !committee.' . PHP_EOL . 'Der er publiceret !meeting_type til !meeting_name !meeting_date.');
    $setting_array['os2dagsorden_meeting_import']['os2dagsorden_follows_committee_send_notification'] = variable_get('os2dagsorden_follows_committee_send_notification', FALSE);
    $setting_array['os2dagsorden_meeting_import']['os2dagsorden_send_timespan_of_notification'] = variable_get('os2dagsorden_send_timespan_of_notification', 10);

    $setting_array['os2dagsorden_meeting_import']['os2dagsorden_add_type_prefix'] = variable_get('os2dagsorden_add_type_prefix', 'true');
    $setting_array['os2dagsorden_meeting_import']['os2dagsorden_committee_category_pol'] = variable_get('os2dagsorden_committee_category_pol', FALSE);
    $setting_array['os2dagsorden_meeting_import']['os2dagsorden_committee_category_org'] = variable_get('os2dagsorden_committee_category_org', FALSE);

    if (module_exists('os2web_pdf_conversion_manager')) {
	$setting_array['os2dagsorden_file_import']['os2web_copied_filetype'] = variable_get('os2web_copied_filetype', OS2WEB_COPIED_FILETYPE);
        $setting_array['os2dagsorden_file_import']['os2web_convertion_dir'] = variable_get('os2web_convertion_dir', OS2WEB_CONVERTION_DIR);
    }

    if (module_exists('os2dagsorden_pdf2htmlex')) {
	$setting_array['os2dagsorden_pdf2htmlex_settings']['os2dagsorden_pdf2htmlex_path'] = variable_get('os2dagsorden_pdf2htmlex_path', "");
	$setting_array['os2dagsorden_pdf2htmlex_settings']['pdf2html_rendering_path'] = variable_get('pdf2html_rendering_path', '');
    }

    $setting_array['os2dagsorden_political_organizational_settings']['os2dagsorden_show_meeting_category'] = variable_get('os2dagsorden_show_meeting_category');
    $setting_array['os2dagsorden_political_organizational_settings']['os2dagsorden_user_default_meeting_category']= variable_get('os2dagsorden_user_default_meeting_category', 'pol');
    $setting_array['os2dagsorden_political_organizational_settings']['os2dagsorden_default_meeting_cateroty'] = variable_get('os2dagsorden_default_meeting_cateroty','pol');


    $conf = ultimate_cron_get_settings("os2dagsorden_importer_cron");
    $setting_array['os2dagsorden_cron_job_freq']['os2dagsorden_importer_cron'] = isset($conf['rules']) ? implode(';', $conf['rules']) : variable_get('ultimate_cron_rule', ULTIMATE_CRON_RULE);
    $conf = ultimate_cron_get_settings("os2web_esdh_provider_cron");
    $setting_array['os2dagsorden_cron_job_freq']['os2web_esdh_provider_cron'] = isset($conf['rules']) ? implode(';', $conf['rules']) : variable_get('ultimate_cron_rule', ULTIMATE_CRON_RULE);
    $conf = ultimate_cron_get_settings("os2dagsorden_pdf2htmlex_cron");
    $setting_array['os2dagsorden_cron_job_freq']['os2dagsorden_pdf2htmlex_cron'] = isset($conf['rules']) ? implode(';', $conf['rules']) : variable_get('ultimate_cron_rule', ULTIMATE_CRON_RULE);
    $conf = ultimate_cron_get_settings("os2dagsorden_adlib_api_cron");
    $setting_array['os2dagsorden_cron_job_freq']['os2dagsorden_adlib_api_cron'] = isset($conf['rules']) ? implode(';', $conf['rules']) : variable_get('ultimate_cron_rule', ULTIMATE_CRON_RULE);
  
    if (module_exists('os2dagsorden_importer')){
	$setting_array['os2dagsorden_pws_sofd_group']['os2dagsorden_pws_use_local_copy'] = variable_get('os2dagsorden_pws_use_local_copy');
	$setting_array['os2dagsorden_pws_sofd_group']['os2dagsorden_pws_v_meetings_url'] = variable_get('os2dagsorden_pws_v_meetings_url');
	$setting_array['os2dagsorden_pws_sofd_group']['os2dagsorden_pws_v_meetinggroups_url'] = variable_get('os2dagsorden_pws_v_meetinggroups_url');
	$setting_array['os2dagsorden_pws_sofd_group']['os2dagsorden_pws_v_acadregroups_url'] = variable_get('os2dagsorden_pws_v_acadregroups_url');
    }

    $setting_array['os2dagsorden_help_text_placeholder']['os2dagsorden_upcoming_meetings_help_text'] = variable_get('os2dagsorden_upcoming_meetings_help_text', 'Her vises de kommende 5 møder i "Mine udvalg". Det vil sige udvalg som man enten er medlem af eller følger. Udvalgene kan ses i boksene "Medlem af" og "Jeg følger" i højremenuen. Der er ikke en dagsorden tilgængelig før status er angivet til Dagsorden eller Dagsorden+.');
    $setting_array['os2dagsorden_help_text_placeholder']['os2dagsorden_meetings_search_help_text'] = variable_get('os2dagsorden_meetings_search_help_text', 'Her vises de møder der indeholdt møder, punkter eller bilag der matchede dine søgekriterier. Søgeresultatet vises på mødeniveau i listen.');
    $setting_array['os2dagsorden_help_text_placeholder']['os2dagsorden_meetings_search_block_help_text'] = variable_get('os2dagsorden_meetings_search_block_help_text', 'Her kan der søges i dagsordenspunkters tekst og i bilagenes fritekst, hvis sidstnævnte er konverteret til html. Søgning kan filtreres via dato, udvalg og søgeord.');
    $setting_array['os2dagsorden_help_text_placeholder']['os2dagsorden_last_8_meetings_help_text'] = variable_get('os2dagsorden_last_8_meetings_help_text', 'Her vises de seneste 8 møder i alle mødefora. Der er ikke et referat tilgængeligt før status er angivet til Referat eller Referat+.');
    $setting_array['os2dagsorden_help_text_placeholder']['os2dagsorden_annotator_help_text'] = variable_get('os2dagsorden_annotator_help_text', 'Hvis du ønsker at lave en kommentar til et ord eller et afsnit, så marker blot dette hvorefter du får mulighed for at indtaste kommentaren.');
    $setting_array['os2dagsorden_help_text_placeholder']['os2dagsorden_calendar_help_text'] = variable_get('os2dagsorden_calendar_help_text', 'Her findes en dags- eller månedskalender med links til dagsordner og referater hvis de er publicerede. Det er muligt at eksportere møderne til en fil, som så kan importeres til egen kalender, eks. i Outlook.');
    $setting_array['os2dagsorden_help_text_placeholder']['os2dagsorden_user_committees_help_text'] = variable_get('os2dagsorden_user_committees_help_text', 'Her kan du se de udvalg du er medlem af. Ret henvendelse til Direktionssekretariatet hvis du mener det skal ændres.');
    $setting_array['os2dagsorden_help_text_placeholder']['os2dagsorden_user_follows_help_text'] = variable_get('os2dagsorden_user_follows_help_text', 'Her kan du se de udvalg du er sat op til at følge. Følger betyder at du kun kan se åbne punkter og Følger+ betyder at du også kan se lukkede punkter. Ret henvendelse til Direktionssekretariatet hvis du mener det skal ændres.');

    $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_general_placeholder']['os2dagsorden_title_general_log_off'] = variable_get('os2dagsorden_title_general_log_off', 'Log af');
    $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_general_placeholder']['os2dagsorden_title_general_search'] = variable_get('os2dagsorden_title_general_search', 'Søg');

    $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_frontpage_placeholder']['os2dagsorden_title_frontpage_coming_meetings'] = variable_get('os2dagsorden_title_frontpage_coming_meetings', 'Kommende møder i mine udvalg');
    $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_frontpage_placeholder']['os2dagsorden_title_frontpage_last_8_meetings'] = variable_get('os2dagsorden_title_frontpage_last_8_meetings', 'Seneste 8 møder i mine udvalg');
    $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_frontpage_placeholder']['os2dagsorden_title_frontpage_calendar'] = variable_get('os2dagsorden_title_frontpage_calendar', 'Kalender');
    $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_frontpage_placeholder']['os2dagsorden_title_frontpage_member_of'] = variable_get('os2dagsorden_title_frontpage_member_of', 'Medlem af');
    $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_frontpage_placeholder']['os2dagsorden_title_frontpage_following'] = variable_get('os2dagsorden_title_frontpage_following', 'Jeg følger');
    $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_frontpage_placeholder']['os2dagsorden_title_frontpage_account_settings'] = variable_get('os2dagsorden_title_frontpage_account_settings', 'Konto indstillinger');
    $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_frontpage_placeholder']['os2dagsorden_title_frontpage_home'] = variable_get('os2dagsorden_title_frontpage_home', 'Hjem');
    $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_frontpage_placeholder']['os2dagsorden_title_frontpage_halfyear_calendar'] = variable_get('os2dagsorden_title_frontpage_halfyear_calendar', 'Halvårs-kalender');

    $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_meeting_placeholder']['os2dagsorden_title_meeting_status'] = variable_get('os2dagsorden_title_meeting_status', 'Status');
    $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_meeting_placeholder']['os2dagsorden_title_meeting_meeting'] = variable_get('os2dagsorden_title_meeting_meeting', 'Møde');
    $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_meeting_placeholder']['os2dagsorden_title_meeting_date'] = variable_get('os2dagsorden_title_meeting_date', 'Dato');
    $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_meeting_placeholder']['os2dagsorden_title_meeting_location'] = variable_get('os2dagsorden_title_meeting_location', 'Lokation');
    $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_meeting_placeholder']['os2dagsorden_title_meeting_comments'] = variable_get('os2dagsorden_title_meeting_comments', 'Bemærkninger');
    $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_meeting_placeholder']['os2dagsorden_title_meeting_special_comments'] = variable_get('os2dagsorden_title_meeting_special_comments', 'Særlige forhold');
    $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_meeting_placeholder']['os2dagsorden_title_meeting_participants'] = variable_get('os2dagsorden_title_meeting_participants', 'Deltagere');
    $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_meeting_placeholder']['os2dagsorden_title_meeting_cancelled_participants'] = variable_get('os2dagsorden_title_meeting_cancelled_participants', 'Afbud / Fraværende');
    $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_meeting_placeholder']['os2dagsorden_title_meeting_agenda'] = variable_get('os2dagsorden_title_meeting_agenda', 'Dagsorden:');
    $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_meeting_placeholder']['os2dagsorden_title_meeting_closed_agenda'] = variable_get('os2dagsorden_title_meeting_closed_agenda', 'Lukket Dagsorden:');
    $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_meeting_placeholder']['os2dagsorden_title_meeting_committee'] = variable_get('os2dagsorden_title_meeting_committee', 'Udvalg');
    $setting_array['os2dagsorden_terminology_placeholder']['os2dagsorden_terminology_meeting_placeholder']['os2dagsorden_title_meeting_new_speaker_paper'] = variable_get('os2dagsorden_title_meeting_new_speaker_paper', 'Nyt talepapir');

    print os2dagsorden_settings_write_ini_file($setting_array, TRUE);
    print $content;
}

/**
 * Flushed the preferences of all the users regarding the calendar (pol/org)
 *
 * @return none
 */
function os2dagsorden_settings_flush_calendar_preferences(){
    $users = db_select('users', 'u')
	  ->fields('u', array('uid'))
	  ->execute()
	  ->fetchAll();
    foreach ($users as $user) {
      if ($user->uid == 0)
	continue;
      
      $user = user_load($user->uid);
      $user->field_user_meetings_category['und'] = array();
      user_save($user);
    }
    
    drupal_set_message('All users calendar preferences have been flushed');
    drupal_goto('admin/config');
}

function os2dagsorden_settings_committee_autocomplete_callback($string = '') {
    $vid = db_select('taxonomy_vocabulary', 'tv')
            ->fields('tv', array('vid'))
            ->condition('machine_name', 'os2web_meetings_tax_committee')
            ->execute()
            ->fetchField();
    $vocabulary_terms = taxonomy_get_tree($vid);
    $array = drupal_explode_tags($string);
    $last_string = trim(array_pop($array));
    $matches = array();
    $prefix = count($array) ? implode(', ', $array) . ', ' : '';
    foreach ($vocabulary_terms as $term)
        $terms[$prefix . $term->name] = $term->name;
    drupal_json_output($terms);
}

function os2dagsorden_settings_views_pre_render(&$view) {
    //print_r($view->name . ' ');
  if ($view->name == 'user_committee') {
    $view->build_info['title'] = variable_get('os2dagsorden_title_frontpage_member_of', 'Medlem af');
  } if ($view->name == 'user_follow_committees') {
    $view->build_info['title'] = variable_get('os2dagsorden_title_frontpage_following', 'Jeg følger');
  } if ($view->name == 'seneste_8_m_der_i_de_st_ende_politiske_udvalg_'){
    $view->build_info['title'] = variable_get('os2dagsorden_title_frontpage_last_8_meetings', 'Seneste 8 møder i mine udvalg');
  } if ($view->name == 'meeting_details'){
    //print_r("<pre>");
    //dpr($view->display_handler->options['header']);
    //print_r("</pre>");
  }
}

function os2dagsorden_settings_views_pre_view(&$view, &$display_id, &$args) {
  if ($view->name == 'seneste_8_m_der_i_de_st_ende_politiske_udvalg_'){
    $view->display_handler->options['fields']['field_os2web_meetings_type']['label'] = variable_get('os2dagsorden_title_meeting_status', 'Status');
    $view->display_handler->options['fields']['php_2']['label'] = variable_get('os2dagsorden_title_meeting_meeting', 'Møde');
    $view->display_handler->options['fields']['field_os2web_meetings_date']['label'] = variable_get('os2dagsorden_title_meeting_date', 'Dato');
    $view->display_handler->options['fields']['php_4']['label'] = variable_get('os2dagsorden_title_meeting_location', 'Lokation');
  } elseif ($view->name == 'meetings_search'){
    $view->display_handler->options['fields']['php_7']['label'] = variable_get('os2dagsorden_title_meeting_status', 'Status');
    $view->display_handler->options['fields']['php_2']['label'] = variable_get('os2dagsorden_title_meeting_meeting', 'Møde');
    $view->display_handler->options['fields']['field_os2web_meetings_date']['label'] = variable_get('os2dagsorden_title_meeting_date', 'Dato');
  } elseif ($view->name == 'kommende_m_der_i_mine_udvalg'){
    $view->display_handler->options['fields']['php_2']['label'] = variable_get('os2dagsorden_title_meeting_meeting', 'Møde');
  } elseif ($view->name == 'meeting_details'){
    if ($view->display_handler->options['fields']['title']['id'])
        $view->display_handler->options['fields']['title']['label'] = variable_get('os2dagsorden_title_meeting_meeting', 'Møde');
    if ($view->display_handler->options['fields']['field_os2web_meetings_location']['id'])
       $view->display_handler->options['fields']['field_os2web_meetings_location']['label'] = variable_get('os2dagsorden_title_meeting_location', 'Lokation');
    if ($view->display_handler->options['fields']['php_3']['id'])
       $view->display_handler->options['fields']['php_3']['label'] = variable_get('os2dagsorden_title_meeting_committee', 'Udvalg');
    if ($view->display_handler->options['fields']['field_os2web_meetings_comments']['id'])
       $view->display_handler->options['fields']['field_os2web_meetings_comments']['label'] = variable_get('os2dagsorden_title_meeting_comments', 'Bemærkninger');
    if ($view->display_handler->options['fields']['field_os2web_meetings_conditions']['id'])
       $view->display_handler->options['fields']['field_os2web_meetings_conditions']['label'] = variable_get('os2dagsorden_title_meeting_special_comments', 'Særlige forhold');
    if ($view->display_handler->options['fields']['php']['ui_name'] == 'Participants')
       $view->display_handler->options['fields']['php']['label'] = variable_get('os2dagsorden_title_meeting_participants', 'Deltagere');
    if ($view->display_handler->options['fields']['php']['ui_name'] == 'Participants (Cancelled)')
        $view->display_handler->options['fields']['php']['label'] = variable_get('os2dagsorden_title_meeting_cancelled_participants', 'Afbud / Fraværende');
  }
}

function os2dagsorden_settings_write_ini_file($assoc_arr, $has_sections=FALSE) { 
    $content = "";
    if ($has_sections){ 
        foreach ($assoc_arr as $key=>$elem){ 
            $content .= "[".$key."]\n"; 
            foreach ($elem as $key2=>$elem2){ 
                if(is_array($elem2)){ 
                    for($i=0;$i<count($elem2);$i++){ 
                        $content .= $key2."[] = \"".$elem2[$i]."\"\n"; 
                    } 
                } 
                else if($elem2=="") $content .= $key2." = \n"; 
                else $content .= $key2." = \"".$elem2."\"\n"; 
            } 
        } 
    } 
    else { 
        foreach ($assoc_arr as $key=>$elem){ 
            if(is_array($elem)){ 
                for($i=0;$i<count($elem);$i++){ 
                    $content .= $key."[] = \"".$elem[$i]."\"\n"; 
                } 
            } 
            else if($elem=="") $content .= $key." = \n"; 
            else $content .= $key." = \"".$elem."\"\n"; 
        } 
    }

    return $content;
}

function os2dagsorden_settings_form_alter(&$form, $form_state, $form_id) {
  if($form['#id'] == 'views-exposed-form-meetings-search-page') {
    if (empty($_GET['from_date']))  {
	$form['from_date']['value']['#default_value'] = date('Y-m-d', strtotime('-' . variable_get('os2dagsorden_search_startdate', 1) . ' months'));
    }
    if (empty($_GET['to_date']))  {
	$form['to_date']['value']['#default_value'] = date('Y-m-d', strtotime('+' . variable_get('os2dagsorden_search_enddate', 1) . ' months'));
    }
    $form['submit']['#value'] = variable_get('os2dagsorden_title_general_search', 'Søg');
  }

  if ($form_id == 'os2web_meetings_spaper_node_form'){
    global $user;
    $form['body']['und'][0]['#default_value'] .= empty($user->field_user_full_name['und'][0]['value']) ? $user->name : $user->field_user_full_name['und'][0]['value'];
    $form['body']['und'][0]['#default_value'] .= ', ' . date('d-m-Y') . ':';
  }
}

function os2dagsorden_settings_block_view_alter(&$data, $block){
//print_r($block->delta . ' ');
    switch ($block->delta) {
	case '-exp-meetings_search-page':
	    $data['content']['#markup'] = '<div class="help-button" title="' . variable_get('os2dagsorden_meetings_search_block_help_text', 'Her kan der søges i dagsordenspunkters tekst og i bilagenes fritekst, hvis sidstnævnte er konverteret til html. Søgning kan filtreres via dato, udvalg og søgeord.') . '"></div>' . $data['content']['#markup'];
            $block->title = variable_get('os2dagsorden_title_general_search', 'Søg');
	    break;
        case 'events-block_1':
            $block->title = variable_get('os2dagsorden_title_frontpage_calendar', 'Kalender');
            break;
        case 'menu-sidepane-menu':
            foreach ($data['content'] as &$menu_item){
                if ($menu_item['#theme'] == 'menu_link__menu_sidepane_menu'){//filtering on actual menus
                    if ($menu_item['#title'] == 'Hjem')//Hjem
                        $menu_item['#title'] = variable_get('os2dagsorden_title_frontpage_home', 'Hjem');
                    if ($menu_item['#title'] == 'Halvårs-kalender')//Halvårs-kalender
                        $menu_item['#title'] = variable_get('os2dagsorden_title_frontpage_halfyear_calendar', 'Halvårs-kalender');
                }
            }
            break;
    }
}