<?php

/**
 * @file
 * This module implements SBSYS ESDH backend for use in os2web
 */

define('MM_IMPORT_DIR', 'public://sbsys_ishoj');
define('MM_DEFAULT_APPROVED', '11');
define('MM_DEFAULT_BANNED_CHAR', '&#xC;');

/**
 * Implements hook_ctools_plugin_directory().
 *
 * Register as provider of esdh plugins
 */
function os2web_sbsys_ishoj_esdh_ctools_plugin_directory($module, $plugin) {
  if ($module == 'os2web_esdh_provider') {
    return "plugins/$plugin";
  }
}

/**
 * Implements hook_form_alter().
 *
 * Add configuration to the settings form.
 */
function os2web_sbsys_ishoj_esdh_form_os2web_settings_settings_form_alter(&$form, &$form_state) {
  // MM configuration.
  $form['meetings'] = array(
    '#type' => 'fieldset',
    '#title' => 'Referat import',
    '#description' => 'Indstillinger der vedrører importen af SBsys referater og dagsordener.',
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
  $form['meetings']['os2web_sbsys_ishoj_esdh_mm_path'] = array(
    '#type' => 'textfield',
    '#title' => 'Sti til sbsys publish folder.',
    '#description' => 'Dette er stien hvor ESDH publisere .XML filer til.',
    '#default_value' => variable_get('os2web_sbsys_ishoj_esdh_mm_path', MM_IMPORT_DIR),
  );
  $form['meetings']['os2web_sbsys_ishoj_esdh_approved_committees'] = array(
    '#type' => 'textfield',
    '#title' => 'Godkendte Udvalg',
    '#maxlength' => 2000,
    '#description' => 'Komma sepereret liste over udvalgs-id der er godkendt til publisering.',
    '#default_value' => variable_get('os2web_sbsys_ishoj_esdh_approved_committees', MM_DEFAULT_APPROVED),
  );
  $form['meetings']['os2web_sbsys_ishoj_esdh_banned_special_char'] = array(
    '#type' => 'textfield',
    '#title' => 'Ikke standard XML tegn der skal fjernes ved import',
    '#maxlength' => 200,
    '#description' => 'Komma sepereret liste over ikke standard tegn der skal fjernes ved import.',
    '#default_value' => variable_get('os2web_sbsys_ishoj_esdh_banned_special_char', MM_DEFAULT_BANNED_CHAR),
  );
  $form['meetings']['os2web_meetings_import_closed_agenda'] = array(
    '#type' => 'checkbox',
    '#title' => t('Import closed agenda'),
    '#description'=>t('This decides if closed agenda is or is not to be imported'),
    '#default_value' => variable_get('os2web_meetings_import_closed_agenda', false),
  );
}

/**
 * Implements hook_os2web_help().
 */
function os2web_sbsys_ishoj_esdh_os2web_help($sections) {

  // Content types.
  $sections['contenttype'] .= t('<p><b>Meeting node:</b> Add <a href="@url" target="_blank">meetings</a> directly.<br /><i><a href="@sbsys" target="_blank">See the advanced documentation for the OS2web eDoc module</a>(.pdf)</i></p>', array('@url' => url('node/add/os2web_meetings_meeting'), '@sbsys' => file_create_url(drupal_get_path('module', 'os2web_sbsys_ishoj_esdh') . '/os2web_sbsys_modul_setup.pdf')));
  $sections['import'] .= t('<p><b>Import agenades:</b> <a href="@sbsys" target="_blank">See the advanced documentation for the OS2web eDoc module import</a>(.pdf)</i></p>', array('@url' => url('node/add/os2web_meetings_meeting'), '@sbsys' => file_create_url(drupal_get_path('module', 'os2web_sbsys_ishoj_esdh') . '/os2web_sbsys_modul_setup.pdf')));
  $sections['documentation'] .= t('<p><b>PDF documentation for sbsys:</b> <a href="@sbsys" target="_blank">Documentation for the OS2web eDoc module</a>(.pdf)</i></p>', array('@url' => url('node/add/os2web_meetings_meeting'), '@sbsys' => file_create_url(drupal_get_path('module', 'os2web_sbsys_ishoj_esdh') . '/os2web_sbsys_modul_setup.pdf')));
  return $sections;

}



/**
 * Implements hook_help().
 */
function os2web_sbsys_ishoj_esdh_help($path, $arg) {
  switch ($path) {
    case 'admin/help#os2web_sbsys_ishoj_esdh':
      // TODO.
      return t('Se the OS2web documentation under "help" for details. If you don not have that please activate the OS2web Help module');
  }
}
