<?php
/**
 * os2dagsorden_importer
 *
 * PHP version 5
 *
 * @category OS2Dagsorden
 * @package  OS2Dagsorden_Importer
 * @author   Stanislav Kutasevits <stan@bellcom.dk>
 * @license  http://www.gnu.org/licenses/gpl-2.0.html GNU General Public License, version 2
 * @link     http://bellcom.dk
 */
define('DEFAULT_ACADRE_VIEWS_IMPORT_DIR', 'public://acadre_views');

/**
 * Implementation of hook_menu().
 *
 * @return array of links.
 */
function os2dagsorden_importer_menu() {
    $items = array();

    $items['os2dagsorden/sync'] = array(
        'page callback' => 'os2dagsorden_importer_sync',
        'access arguments' => array('administer os2web'),
        'type' => MENU_CALLBACK,
    );
    $items['admin/config/os2web/importer'] = array(
        'title' => 'SOFD importer',
        'access arguments' => array('administer os2web'),
        'page callback' => '_os2dagsorden_importer_page_callback',
        'type' => MENU_LOCAL_TASK,
        'position' => 'left',
        'weight' => -200,
    );
   
    return $items;
}


/**
 * Access callback. Returns SOFD importer form
  */
function _os2dagsorden_importer_page_callback() {
    return theme('table', array('header' => $head, 'rows' => $rows)) .
            '<h2>' . t('Run SOFD importer') . '</h2>' .
            render(drupal_get_form('_os2dagsorden_importer_form'));
}

function _os2dagsorden_importer_form() {
    $form = array();
    $form['run'] = array(
        '#type' => 'submit',
        '#value' => t('Run SOFD importer'),
    );
    return $form;
}

function _os2dagsorden_importer_form_submit(&$form_state, $form) {
  os2dagsorden_importer_import_user_committees_improved();
  drupal_set_message('User rights updated successfully','status' );
}

/**
 * Link fallback. Fires all the imports.
 *
 * @return none
 */
function os2dagsorden_importer_sync() {
   os2dagsorden_importer_import_user_committees_improved();
    //os2dagsorden_importer_import_user_committees();
    //os2dagsorden_importer_import_committees();
    //os2dagsorden_importer_import_meetings();
}

/**
 * Implementation of hook_cronapi().
 */
function os2dagsorden_importer_cronapi($op, $job = NULL) {
  switch ($op) {
    case 'list':
      return array('os2dagsorden_importer_cron' => t("Imports meetings, user's committees, user positions and committees"));
  }
}
/**
 * Implementation of hook_cron().
 * Fires all imports.
 *
 * @return none
 */
function os2dagsorden_importer_cron() {
    os2dagsorden_importer_import_user_committees();
    os2dagsorden_importer_import_committees();   
    os2dagsorden_importer_import_meetings();    
}
/**
 * Imports the user committees (user roles: member of, follows, follows+) from the remotely located xml view.
 * Delete user committees(user roles: member of, follows, follows+), that are not found in the SOFD system any longer.
 * @return none
 */

function os2dagsorden_importer_import_user_committees_improved(){
  $userCommittees=  os2dagsorden_importer_load_user_committees_from_xml(); 
  _os2dagsorden_importer_process_user_committees_improved($userCommittees);  
}

/**
 * Imports the user committees (user roles: member of, follows, follows+) from the remotely located xml view.
 *
 * @return none
 */
function os2dagsorden_importer_import_user_committees() {
   $userCommittees=  os2dagsorden_importer_load_user_committees_from_xml(); 
   _os2dagsorden_importer_process_user_committees($userCommittees);
}

function os2dagsorden_importer_load_user_committees_from_xml(){
    if (!variable_get('os2dagsorden_pws_use_local_copy')){
      $url = curl_init(variable_get('os2dagsorden_pws_v_meetinggroups_url'));

      if (variable_get('os2web_pws_proxy')) {
	  curl_setopt($url, CURLOPT_PROXY, variable_get('os2web_pws_proxy_host'));
	  curl_setopt($url, CURLOPT_PROXYPORT, variable_get('os2web_pws_proxy_port'));
	  curl_setopt($url, CURLOPT_HTTPPROXYTUNNEL, TRUE);
      }

      curl_setopt($url, CURLOPT_RETURNTRANSFER, TRUE);
      $userCommittees_raw = curl_exec($url);
      $userCommittees = new SimpleXMLElement($userCommittees_raw);
    } else {
      $userCommittees = simplexml_load_file(DEFAULT_ACADRE_VIEWS_IMPORT_DIR . '/V_web_MeetingGroups.xml');
    }
    return $userCommittees;
}

/**
 * Imports the committees (udvalg) from the remotely located xml view.
 *
 * @return none
 */
function os2dagsorden_importer_import_committees() {
    if (!variable_get('os2dagsorden_pws_use_local_copy')){
      $url = curl_init(variable_get('os2dagsorden_pws_v_acadregroups_url'));

      if (variable_get('os2web_pws_proxy')) {
	  curl_setopt($url, CURLOPT_PROXY, variable_get('os2web_pws_proxy_host'));
	  curl_setopt($url, CURLOPT_PROXYPORT, variable_get('os2web_pws_proxy_port'));
	  curl_setopt($url, CURLOPT_HTTPPROXYTUNNEL, TRUE);
      }

      curl_setopt($url, CURLOPT_RETURNTRANSFER, TRUE);
      $acadreGroups_raw = curl_exec($url);
      $acadreGroups = new SimpleXMLElement($acadreGroups_raw);
    } else {
      $acadreGroups = simplexml_load_file(DEFAULT_ACADRE_VIEWS_IMPORT_DIR . '/V_web_AcadreGroups.xml');
    }
      _os2dagsorden_importer_process_committees($acadreGroups);
}

/**
 * Imports the meetings from the remotely located xml view.
 *
 * @return none
 */
function os2dagsorden_importer_import_meetings() {
    if (!variable_get('os2dagsorden_pws_use_local_copy')){
      $url = curl_init(variable_get('os2dagsorden_pws_v_meetings_url'));

      if (variable_get('os2web_pws_proxy')) {
	  curl_setopt($url, CURLOPT_PROXY, variable_get('os2web_pws_proxy_host'));
	  curl_setopt($url, CURLOPT_PROXYPORT, variable_get('os2web_pws_proxy_port'));
	  curl_setopt($url, CURLOPT_HTTPPROXYTUNNEL, TRUE);
      }
      curl_setopt($url, CURLOPT_RETURNTRANSFER, TRUE);
      $meetings_raw = curl_exec($url);
      $meetings = new SimpleXMLElement($meetings_raw);
    } else {
      $meetings = simplexml_load_file(DEFAULT_ACADRE_VIEWS_IMPORT_DIR . '/V_web_Meetings.xml');
    }
    _os2dagsorden_importer_process_meetings($meetings);
}

function _os2dagsorden_importer_process_user_committees($xml_file){
  _os2dagsorden_importer_process_user_committees_update($xml_file);  
}

function _os2dagsorden_importer_process_user_committees_improved($xml_file){
  _os2dagsorden_importer_process_user_committees_update($xml_file);  
  _os2dagsorden_importer_process_user_committees_delete($xml_file);
}

/**
 * Helper function. Processes the user committees xml file.
 * Delegates to create/delete method based on the xml controller.
 *
 * @param mixed $xml_file xml file
 *
 * @return none
 */
function _os2dagsorden_importer_process_user_committees_update($xml_file) {
    $result = $xml_file->xpath('//Row');

    foreach ($result as $row) {
        $xml_data = array(
            'user_pos_id' => (int) array_shift($row->xpath('SystemID')),
            'committee_id' => (int) array_shift($row->xpath('GroupID')),
            'committee_name' => (string) array_shift($row->xpath('GroupLongName')),
            'follower_id' => (int) array_shift($row->xpath('FollowerID')),
            'follower_initials' => (string) array_shift($row->xpath('FollowerInitials')),
            'follower_name' => (string) array_shift($row->xpath('FollowerName')),
            'follower_plus_id' => (int) array_shift($row->xpath('FollowerPlusID')),
            'follower_plus_initials' => (string) array_shift($row->xpath('FollowerPlusInitials')),
            'follower_plus_name' => (string) array_shift($row->xpath('FollowerPlusName')),
            'follower_plus_plus_id' => (int) array_shift($row->xpath('FollowerPlusPlusID')),
            'follower_plus_plus_initials' => (string) array_shift($row->xpath('FollowerPlusPlusInitials')),
            'follower_plus_plus_name' => (string) array_shift($row->xpath('FollowerPlusPlusName')),
            'member_id' => (int) array_shift($row->xpath('MemberID')),
            'member_name' => (string) array_shift($row->xpath('MemberName')),
            'member_start_date' => (string) array_shift($row->xpath('MemberStartDate')),
            'member_end_date' => (string) array_shift($row->xpath('MemberEndDate')),
            'member_initials' => (string) array_shift($row->xpath('MemberInitials')),
            'role' => (string) array_shift($row->xpath('Role')),
            'role_priority' => (int) array_shift($row->xpath('RolePriority')),
            'deactivated' => (int) array_shift($row->xpath('Deactivated')),
            'meeting_category' => (string) array_shift($row->xpath('CalendarCategory')),
        );


        //getting user
        $user = '';
        //trying to get user from "Is member of" association 
        if ($xml_data['member_id'] != 0) {
            $query = new EntityFieldQuery();
            $query->entityCondition('entity_type', 'user')
                    ->fieldCondition('field_user_id', 'value', intval($xml_data['member_id']), '=');

            $result = $query->execute();
            if (isset($result['user'])) {
                $uids = array_keys($result['user']);
                $user = reset(entity_load('user', $uids));
            }

            if (empty($user)) {
                $user = user_load_by_name($xml_data['member_initials']);
            }
        }

        //trying to get user from "Follows" association 
        if ($xml_data['follower_id'] != 0) {
            $query = new EntityFieldQuery();
            $query->entityCondition('entity_type', 'user')
                    ->fieldCondition('field_user_id', 'value', intval($xml_data['follower_id']), '=');

            $result = $query->execute();
            if (isset($result['user'])) {
                $uids = array_keys($result['user']);
                $user = reset(entity_load('user', $uids));
            }
            
            if (empty($user)) {
                $user = user_load_by_name($xml_data['follower_initials']);
            }
        }

        //trying to get user from "Follows+" association 
        if ($xml_data['follower_plus_id'] != 0) {
            $query = new EntityFieldQuery();
            $query->entityCondition('entity_type', 'user')
                    ->fieldCondition('field_user_id', 'value', intval($xml_data['follower_plus_id']), '=');

            $result = $query->execute();
            if (isset($result['user'])) {
                $uids = array_keys($result['user']);
                $user = reset(entity_load('user', $uids));
            }

            if (empty($user)) {
                $user = user_load_by_name($xml_data['follower_plus_initials']);
            }
        }
        
        //trying to get user from "Follows++" association 
        if ($xml_data['follower_plus_plus_id'] != 0) {
            $query = new EntityFieldQuery();
            $query->entityCondition('entity_type', 'user')
                    ->fieldCondition('field_user_id', 'value', intval($xml_data['follower_plus_plus_id']), '=');

            $result = $query->execute();
            if (isset($result['user'])) {
                $uids = array_keys($result['user']);
                $user = reset(entity_load('user', $uids));
            }

            if (empty($user)) {
                $user = user_load_by_name($xml_data['follower_plus_plus_initials']);
            }
        }
                  
        //if the entry is not deleted
        if ($xml_data['deactivated'] == 0) {

            //create committee 
            if ($xml_data['committee_id'] != 0) {
                $com_term = _os2dagsorden_importer_get_committee_by_id($xml_data['committee_id']);

                if (isset($com_term)) {
                    $com_tid = $com_term->tid;
                    if ($xml_data['member_id'] != 0 && !empty($user)) {
                        //add committee to user
                        _os2dagsorden_importer_add_committee_to_user($com_tid, $user);
                    }
                    if ($xml_data['follower_id'] != 0 && !empty($user)) {
                        //add user follows committee
                        _os2dagsorden_importer_add_user_follows_committee($com_tid, $user);
                    }
                    if ($xml_data['follower_plus_id'] != 0 && !empty($user)) {
                        //add user follows committee PLUS
                        _os2dagsorden_importer_add_user_follows_committee_plus($com_tid, $user);
                    }
                    if ($xml_data['follower_plus_plus_id'] != 0 && !empty($user)) {
                        //add user follows committee PLUS
                        _os2dagsorden_importer_add_user_follows_committee_plus_plus($com_tid, $user);
                    }
                }
            }
            if (!empty($user)) {
                //update full name
                if (!empty($xml_data['member_name'])) {
                    if (strcmp($user->field_user_full_name['und'][0]['value'], $xml_data['member_name']) != 0) {
                        _os2dagsorden_importer_set_user_fullname($user, $xml_data['member_name']);
                    }
                }
                if (!empty($xml_data['follower_name'])) {
                    if (strcmp($user->field_user_full_name['und'][0]['value'], $xml_data['follower_name']) != 0) {
                        _os2dagsorden_importer_set_user_fullname($user, $xml_data['follower_name']);
                    }
                }
                if (!empty($xml_data['follower_plus_name'])) {
                    if (strcmp($user->field_user_full_name['und'][0]['value'], $xml_data['follower_plus_name']) != 0) {
                        _os2dagsorden_importer_set_user_fullname($user, $xml_data['follower_plus_name']);
                    }
                }
                
                 if (!empty($xml_data['follower_plus_plus_name'])) {
                    if (strcmp($user->field_user_full_name['und'][0]['value'], $xml_data['follower_plus_plus_name']) != 0) {
                        _os2dagsorden_importer_set_user_fullname($user, $xml_data['follower_plus_plus_name']);
                    }
                }

                //create user role
                if (isset($xml_data['role'])) {
                   _os2dagsorden_importer_add_role_to_user($xml_data, $user, $com_tid);                    
                }

                //update meeting category
                if (isset($xml_data['meeting_category'])) {
                    _os2dagsorden_importer_update_meeting_category($user, $xml_data['meeting_category']);
                }
            }
        } else {
            //unsetting user rights
            if ($xml_data['committee_id'] != 0) {
                $com_term = _os2dagsorden_importer_get_committee_by_id($xml_data['committee_id']);

                if (isset($com_term)) {
                    $com_tid = $com_term->tid;
                    if ($xml_data['member_id'] != 0 && !empty($user)) {
                        //unset is part of
                        _os2dagsorden_importer_unset_committee_from_user($com_tid, $user);
                    }
                    if ($xml_data['follower_id'] != 0 && !empty($user)) {
                        //unset follows committee
                        _os2dagsorden_importer_unset_user_follows_committee($com_tid, $user);
                    }
                    if ($xml_data['follower_plus_id'] != 0 && !empty($user)) {
                        //unset follows committee PLUS
                        _os2dagsorden_importer_unset_user_follows_committee_plus($com_tid, $user);
                    }
                    
                    if ($xml_data['follower_plus_plus_id'] != 0 && !empty($user)) {
                        //unset follows committee PLUS
                        _os2dagsorden_importer_unset_user_follows_committee_plus_plus($com_tid, $user);
                    }
                }
            }
            //deleting role  
            if (!empty($user))
                _os2dagsorden_importer_delete_user_role($xml_data['user_pos_id'], $user);
        }
    }
}

/**
 * Helper function. Processes the user committees xml file.
 * Checks all the SOFD rights and delete those, that are not found in the SOFD system any longer.
 * 
 *  @param mixed $xml_file xml file
 *
 * @return none
 */
function _os2dagsorden_importer_process_user_committees_delete($xml_file){
 $users = db_select('users', 'u')
    ->fields('u', array('uid', 'name'))
    ->execute()
    ->fetchAll();

 foreach ($users as $user) {
    $full_user = user_load($user->uid);
    $userFollowerCommittees = Array();
    $userFollowerPlusCommittees = Array();
    $userFollowerPlusPlusCommittees = Array();
    $userMemberOfCommittees = Array();
    $userSystemID = Array();
    
    //user MemberOf Committee
    $result=$xml_file->xpath('//Row[MemberInitials="' . $user->name . '"]');
    //var_dump($result);
    foreach($result as $xml_data){
      $userSystemID[] = (int) array_shift($xml_data->xpath('SystemID'));
      $com_term = _os2dagsorden_importer_get_committee_by_id((int) array_shift($xml_data->xpath('GroupID')));
       if (isset($com_term)) 
        $userMemberOfCommittees[] = $com_term->tid; 
    
    }
    //user Follower Committee
    $result=$xml_file->xpath('//Row[FollowerInitials="'.$user->name.'"]');
    foreach($result as $xml_data){
      $userSystemID[] = (int) array_shift($xml_data->xpath('SystemID'));  
      $com_term = _os2dagsorden_importer_get_committee_by_id((int) array_shift($xml_data->xpath('GroupID')));
       if (isset($com_term)) 
        $userFollowerCommittees[] = $com_term->tid;
    }
    //user Follower Plus Committee
    $result=$xml_file->xpath('//Row[FollowerPlusInitials="'.$user->name.'"]');
    foreach($result as $xml_data){
      $userSystemID[] = (int) array_shift($xml_data->xpath('SystemID'));  
      $com_term = _os2dagsorden_importer_get_committee_by_id((int) array_shift($xml_data->xpath('GroupID')));
       if (isset($com_term)) 
        $userFollowerPlusCommittees[] = $com_term->tid;
    }
    //user Follower PlusPlus Committee
    $result=$xml_file->xpath('//Row[FollowerPlusPlusInitials="'.$user->name.'"]');
    foreach($result as $xml_data){
      $userSystemID[] = (int) array_shift($xml_data->xpath('SystemID'));  
      $com_term = _os2dagsorden_importer_get_committee_by_id((int) array_shift($xml_data->xpath('GroupID')));
       if (isset($com_term)) 
        $userFollowerPlusPlusCommittees[] = $com_term->tid;
    }
   if (isset($full_user->field_user_committee['und'])) {
   foreach ($full_user->field_user_committee['und'] as $com) { 
    if (!in_array($com['tid'], $userMemberOfCommittees)){
     //unset is part of
      _os2dagsorden_importer_unset_committee_from_user($com['tid'], $full_user); }       
    }
   }
  if (isset($full_user->field_follows_committee['und'])) {
   foreach ($full_user->field_follows_committee['und'] as $com) {  
    if (!in_array($com['tid'], $userFollowerCommittees)){
     //unset is part of
     _os2dagsorden_importer_unset_user_follows_committee($com['tid'], $full_user); 
    }
   }
  }
   if (isset($full_user->field_follows_committee_plus['und'])) {
   foreach ($full_user->field_follows_committee_plus['und'] as $com) {        
    if (!in_array($com['tid'], $userFollowerPlusCommittees))
     //unset is part of
     _os2dagsorden_importer_unset_user_follows_committee_plus($com['tid'], $full_user);        
    }
   }
   if (isset($full_user->field_follows_committee_pp['und'])) {
   foreach ($full_user->field_follows_committee_pp['und'] as $com) {        
    if (!in_array($com['tid'], $userFollowerPlusPlusCommittees))
     //unset is part of
     _os2dagsorden_importer_unset_user_follows_committee_plus_plus($com['tid'], $full_user);        
    }
   }
   $user_role_items = field_get_items('user', $full_user, 'field_os2web_user_pos');
    if (is_array($user_role_items)) {
    foreach ($user_role_items as $item) {
     $currnet_role_item = field_collection_field_get_entity($item);
     $pos_id = intval($currnet_role_item->field_os2web_user_pos_id['und'][0]['value']);
     if (!in_array($pos_id, $userSystemID))
      _os2dagsorden_importer_delete_user_role($pos_id, $full_user);
    }
  }
 }
}

/**
 * Helper function. Will update user's full name field
 *
 * @param mixed  $user user object  
 * @param string $name new name
 *
 * @return none
 */
function _os2dagsorden_importer_set_user_fullname($user, $name) {
    $user->field_user_full_name['und'][0]['value'] = $name;
    user_save($user);
}

/**
 * Helper function. Will update user's meetings category
 *
 * @param mixed  $user user object  
 * @param string $category meeting category
 *
 * @return none
 */
function _os2dagsorden_importer_update_meeting_category($user, $category) {
    if (isset($user->field_user_meetings_category['und'])) {
      foreach ($user->field_user_meetings_category['und'] as $user_category){
	if (strcasecmp($user_category['value'], $category) == 0){//already has this category
	  return $user;
	}
      }
    }
    $user->field_user_meetings_category['und'][]['value'] = strtolower($category);
    user_save($user);
}

/**
 * Helper function. Deletes the user role.
 *
 * @param array $xml_data xml
 *
 * @return none
 */
function _os2dagsorden_importer_delete_user_role($user_pos_id, $user) {
    $user_role_items = Array();
    $user_role_items = field_get_items('user', $user, 'field_os2web_user_pos');
    foreach ($user_role_items as $item_id => $item) {
        $currnet_role_item = field_collection_field_get_entity($item);
        if (intval($currnet_role_item->field_os2web_user_pos_id['und'][0]['value']) == intval($user_pos_id)) {
            entity_delete_multiple('field_collection_item', array($item['value']));
            unset($user->field_os2web_user_pos['und'][$item_id]);
            user_save($user);
        }
    }
}

/**
 * Helper function. Returns the committee based on its group id.
 *
 * @param int $com_id committee id
 *
 * @return the committee term, if found.
 */
function _os2dagsorden_importer_get_committee_by_id($com_id){
    $vid = db_select('taxonomy_vocabulary', 'tv')
            ->fields('tv', array('vid'))
            ->condition('machine_name', 'os2web_meetings_tax_committee')
            ->execute()
            ->fetchField();

    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'taxonomy_term')
            ->propertyCondition('vid', $vid)
            ->fieldCondition('field_os2web_meetings_commiteeid', 'value', intval($com_id), '=');

    $result = $query->execute();
    if (isset($result['taxonomy_term'])) {   
        $tids = array_keys($result['taxonomy_term']);
        $tid = reset($tids);
        $term = taxonomy_term_load($tid);
        return $term;
    }
}

/**
 * Helper function. Returns the committee based on its sub id.
 *
 * @param int $com_subid committee sub id
 *
 * @return the committee term, if found.
 */
function _os2dagsorden_importer_get_committee_by_subid($com_subid){
    $vid = db_select('taxonomy_vocabulary', 'tv')
            ->fields('tv', array('vid'))
            ->condition('machine_name', 'os2web_meetings_tax_committee')
            ->execute()
            ->fetchField();
	    
    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'taxonomy_term')
            ->propertyCondition('vid', $vid)
            ->fieldCondition('field_os2web_meetings_com_subid', 'value', intval($com_subid), '=');
	    
    $result = $query->execute();
    if (isset($result['taxonomy_term'])) {   
        $tids = array_keys($result['taxonomy_term']);
        $tid = reset($tids);
        $term = taxonomy_term_load($tid);
        return $term;
    }    
}

/**
 * Helper function. Creates/updates the committee
 *
 * @param mixed $xml_data xml
 *
 * @return the id of created/updated entry.
 */
function _os2dagsorden_importer_create_committee($xml_data) {
    //getting committee by ID
    $term = _os2dagsorden_importer_get_committee_by_id($xml_data['committee_id']);
    
    //no success, getting committee by subid
    if (!isset($term)){
	print_r('here');
	$term = _os2dagsorden_importer_get_committee_by_subid($xml_data['acadre_id']);
        if ($term)
	  $term->field_os2web_meetings_commiteeid['und'][0]['value'] = $xml_data['committee_id'];
    }
	
    //no success, creating new committee
    if (!isset($term)){
	$vid = db_select('taxonomy_vocabulary', 'tv')
            ->fields('tv', array('vid'))
            ->condition('machine_name', 'os2web_meetings_tax_committee') 
            ->execute()
            ->fetchField();
        $term = new stdClass();
        $term->vid = $vid;
        $term->field_os2web_meetings_commiteeid['und'][0]['value'] = $xml_data['committee_id'];
    }

    $term->name = $xml_data['committee_name'];

    if (!empty($xml_data['committee_name_short']))
        $term->field_os2web_meetings_com_shname['und'][0]['value'] = $xml_data['committee_name_short'];
    if (!empty($xml_data['committee_abbr']))
        $term->field_os2web_meetings_com_abbr['und'][0]['value'] = $xml_data['committee_abbr'];

    if (!empty($xml_data['acadre_id'])) {
	//check if is in the list of import committees
	$can_be_imported = FALSE;

	$import_committees = explode(',',variable_get('os2web_meetings_approved_committee'));
	  foreach($import_committees as $imp_com){
	    if (intval($imp_com) == intval($xml_data['acadre_id'])){
	      $can_be_imported = TRUE;
	      break;
	    }
	}
	
        $contains = FALSE;
        if (isset($term->field_os2web_meetings_com_subid['und'])) {
            foreach ($term->field_os2web_meetings_com_subid['und'] as $id_raw) {
                if (intval($id_raw['value']) == intval($xml_data['acadre_id'])) {
                    $contains = TRUE;
                    break;
                }
            }
        }
        if (!$contains) {
            $term->field_os2web_meetings_com_subid['und'][]['value'] = $xml_data['acadre_id'];
        }
    }
    
    if ($can_be_imported){
      taxonomy_term_save($term);
      return $term->tid;
    } else {
      return;
    }
}

/**
 * Helper function. Adds the committee to the user (member of)
 *
 * @param int   $tid  role id
 * @param mixed $user user object
 *
 * @return none
 */
function _os2dagsorden_importer_add_committee_to_user($tid, $user) {
    $user_is_part_of_committee = FALSE;
    if (isset($user->field_user_committee['und'])) {
        foreach ($user->field_user_committee['und'] as $committee_id) {
            if ($tid == $committee_id['tid']) {
                $user_is_part_of_committee = TRUE;
            }
        }
    }

    if (!$user_is_part_of_committee) {
        $user_committees = $user->field_user_committee;
        $user_committees['und'][]['tid'] = $tid;

        $edit = array(
            'field_user_committee' => $user_committees,
        );

        user_save($user, $edit);
    }
}

/**
 * Helper function. Unsets the committee to the user (member of)
 *
 * @param int   $tid  role id
 * @param mixed $user user object
 *
 * @return none
 */
function _os2dagsorden_importer_unset_committee_from_user($tid, $user){
    //composing new array
    $user_committees = array();
    if (isset($user->field_user_committee['und'])) {
        foreach ($user->field_user_committee['und'] as $committee_id) {
	    //add everything except the one that has to be deleted
            if ($tid != $committee_id['tid']) {
                $user_committees['und'][]['tid'] = $committee_id['tid'];
            }
        }
    }

   
    $edit = array(
	'field_user_committee' => $user_committees,
    );

    user_save($user, $edit);
}


/**
 * Helper function. Adds the follows committee to the user
 *
 * @param int   $tid  role id
 * @param mixed $user user object
 *
 * @return none
 */
function _os2dagsorden_importer_add_user_follows_committee($tid, $user) {
    $user_follows_committee = FALSE;
    if (isset($user->field_follows_committee['und'])) {
        foreach ($user->field_follows_committee['und'] as $committee_id) {
            if ($tid == $committee_id['tid']) {
                $user_follows_committee = TRUE;
            }
        }
    }

    if (!$user_follows_committee) {
        $old_list = $user->field_follows_committee;
        $old_list['und'][]['tid'] = $tid;

        $edit = array(
            'field_follows_committee' => $old_list,
        );

        user_save($user, $edit);
    }
}

/**
 * Helper function. Unsets the follows committee of the user
 *
 * @param int   $tid  role id
 * @param mixed $user user object
 *
 * @return none
 */
function _os2dagsorden_importer_unset_user_follows_committee($tid, $user) {
    $user_follows = array();
    if (isset($user->field_follows_committee['und'])) {
        foreach ($user->field_follows_committee['und'] as $committee_id) {
            if ($tid != $committee_id['tid']) {
                $user_follows['und'][]['tid'] = $committee_id['tid'];
            }
        }
    }

    $edit = array(
	'field_follows_committee' => $user_follows,
    );

    user_save($user, $edit);
}

/**
 * Helper function. Adds the follows+ committee to the user
 *
 * @param int   $tid  role id
 * @param mixed $user user object
 *
 * @return none
 */
function _os2dagsorden_importer_add_user_follows_committee_plus($tid, $user) {
    $user_follows_committee_plus = FALSE;
    if (isset($user->field_follows_committee_plus['und'])) {
        foreach ($user->field_follows_committee_plus['und'] as $committee_id) {
            if ($tid == $committee_id['tid']) {
                $user_follows_committee_plus = TRUE;
            }
        }
    }

    if (!$user_follows_committee_plus) {
        $old_list = $user->field_follows_committee_plus;
        $old_list['und'][]['tid'] = $tid;

        $edit = array(
            'field_follows_committee_plus' => $old_list,
        );

        user_save($user, $edit);
    }
}

/**
 * Helper function. Unsets the follows+ committee to the user
 *
 * @param int   $tid  role id
 * @param mixed $user user object
 *
 * @return none
 */
function _os2dagsorden_importer_unset_user_follows_committee_plus($tid, $user) {
    $user_follows_plus = array();
    if (isset($user->field_follows_committee_plus['und'])) {
        foreach ($user->field_follows_committee_plus['und'] as $committee_id) {
            if ($tid != $committee_id['tid']) {
                $user_follows_plus['und'][]['tid'] = $committee_id['tid'];
            }
        }
    }

    $edit = array(
	'field_follows_committee_plus' => $user_follows_plus,
    );

    user_save($user, $edit);
}
/**
 * Helper function. Adds the follows++ committee to the user
 *
 * @param int   $tid  role id
 * @param mixed $user user object
 *
 * @return none
 */
function _os2dagsorden_importer_add_user_follows_committee_plus_plus($tid, $user) {
    $user_follows_committee_plus_plus = FALSE;
    if (isset($user->field_follows_committee_pp['und'])) {
        foreach ($user->field_follows_committee_pp['und'] as $committee_id) {
            if ($tid == $committee_id['tid']) {
                $user_follows_committee_plus_plus = TRUE;
            }
        }
    }

    if (!$user_follows_committee_plus_plus) {
        $old_list = $user->field_follows_committee_pp;
        $old_list['und'][]['tid'] = $tid;

        $edit = array(
            'field_follows_committee_pp' => $old_list,
        );

        user_save($user, $edit);
    }
}

/**
 * Helper function. Unsets the follows+ committee to the user
 *
 * @param int   $tid  role id
 * @param mixed $user user object
 *
 * @return none
 */
function _os2dagsorden_importer_unset_user_follows_committee_plus_plus($tid, $user) {
    $user_follows_plus_plus = array();
    if (isset($user->field_follows_committee_pp['und'])) {
        foreach ($user->field_follows_committee_pp['und'] as $committee_id) {
            if ($tid != $committee_id['tid']) {
                $user_follows_plus_plus['und'][]['tid'] = $committee_id['tid'];
            }
        }
    }

    $edit = array(
	'field_follows_committee_pp' => $user_follows_plus_plus,
    );

    user_save($user, $edit);
}

/**
 * Helper function. Processes the committees xml.
 * Delegates to create committees.
 *
 * @param mixed $xml_file xml file
 *
 * @return none
 */
function _os2dagsorden_importer_process_committees($xml_file) {
    $result = $xml_file->xpath('//Row');

    foreach ($result as $row) {
        $xml_data = array(
            'committee_id' => (int) array_shift($row->xpath('GroupId')),
            'committee_name' => (string) array_shift($row->xpath('GroupLongName')),
            'committee_name_short' => (string) array_shift($row->xpath('GroupShortName')),
            'committee_abbr' => (string) array_shift($row->xpath('GroupAbbreviation')),
            'acadre_name' => (string) array_shift($row->xpath('AcadreName')),
            'acadre_id' => (int) array_shift($row->xpath('AcadreID')),
            'com_start_date' => (string) array_shift($row->xpath('StartDate')),
            'com_end_date' => (string) array_shift($row->xpath('EndDate')),
        );
        if (empty($xml_data['committee_name_short'])) {
            $xml_data['committee_name_short'] = $xml_data['committee_name'];
        }

        _os2dagsorden_importer_create_committee($xml_data);
    }
}

/**
 * Helper function. Processes the meetings xml.
 * Delegates to create meeings, unpublish meetings, create committee function based on controllers.
 *
 * @param mixed $xml_file xml file
 *
 * @return none
 */
function _os2dagsorden_importer_process_meetings($xml_file) {
    $result = $xml_file->xpath('//Row');

    foreach ($result as $row) {
        $xml_data = array(
            'meeting_id' => (int) array_shift($row->xpath('MeetingID')),
            'title' => (string) array_shift($row->xpath('MeetingTitel')),
            'title_short' => trim((string) array_shift($row->xpath('MeetingTitelShort'))),
            'committee_id' => (int) array_shift($row->xpath('GroupID')),
            'committee_name' => (string) array_shift($row->xpath('GroupLongName')),
            'committee_abbr' => (string) array_shift($row->xpath('GroupAbbreviation')),
            'meeting_start_date' => (string) array_shift($row->xpath('MeetingDate')),
            'meeting_start_time' => (string) array_shift($row->xpath('MeetingStartTime')),
            'meeting_end_time' => (string) array_shift($row->xpath('MeetingEndTime')),
            'hex_color' => (string) array_shift($row->xpath('HEXColorCode')),
            'deactivated' => (int) array_shift($row->xpath('Deactivated')),
            'cancelled' => (int) array_shift($row->xpath('Cancelled')),
            'changed' => (int) array_shift($row->xpath('Changed')),
            'meeting_category' => (string) array_shift($row->xpath('MeetingCategory')),
        );

        if ($xml_data['deactivated'] == 0) {
            if (!empty($xml_data['meeting_start_date'])) {//start time
		 if (empty($xml_data['meeting_start_time'])){
		  $xml_data['meeting_start_time'] = "00:01";
		 }
                $xml_data['meeting_start_date'] = substr_replace($xml_data['meeting_start_date'], $xml_data['meeting_start_time'], 11);
            }
            if (!empty($xml_data['meeting_end_time'])){//end time
		$xml_data['meeting_end_date'] = substr_replace($xml_data['meeting_start_date'], $xml_data['meeting_end_time'], 11);
            }
    
	    $term = _os2dagsorden_importer_get_committee_by_id($xml_data['committee_id']);
	    
	    
            if (isset($term))
	      _os2dagsorden_importer_create_meeting($xml_data, $term->tid);
        }
        else {
            _os2dagsorden_importer_unpublish_meeting($xml_data);
        }
    }
}

/**
 * Helper function. Creates/updates the meeting
 *
 * @param array $xml_data entry parameters
 * @param int   $tid      committee id.
 *
 * @return none
 */
function _os2dagsorden_importer_create_meeting($xml_data, $tid) {
    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'node')
            ->fieldCondition('field_os2web_meetings_sofd_id', 'value', intval($xml_data['meeting_id']), '=');

    $result = $query->execute();
    if (isset($result['node'])) {//getting the meeting from meeting ID
        $nids = array_keys($result['node']);
        $node = reset(entity_load('node', $nids));
    }
    else {//if fails, trying to get meeting from date and committee combination. Assuming this is unique
        //getting meeting
        $meeting_start_date_0000 = date('Y-m-d 00:00:00', strtotime($xml_data['meeting_start_date']));
        $meeting_start_date_2359 = date('Y-m-d 23:59:59', strtotime($xml_data['meeting_start_date']));

        $query = new EntityFieldQuery();
        $query->entityCondition('entity_type', 'node')
                ->fieldCondition('field_os2web_meetings_date', 'value', $meeting_start_date_0000, '>=')
                ->fieldCondition('field_os2web_meetings_date', 'value', $meeting_start_date_2359, '<=')
                ->fieldCondition('field_os2web_meetings_committee', 'tid', $tid, '=');
        $result = $query->execute();

        if (isset($result['node'])) {
            $nids = array_keys($result['node']);
            $node = reset(entity_load('node', $nids));
            
            //sofd id is missing, fill it for future use
	    $node->field_os2web_meetings_sofd_id['und'][0]['value'] = intval($xml_data['meeting_id']);
	    node_submit($node);
	    node_save($node);
        }
        else {
            //if fails, creating a new meeting
            $node = new stdClass();
            $node->type = "os2web_meetings_meeting";
            $node->language = LANGUAGE_NONE;

            node_object_prepare($node);
        }
    }
    
    //avoiding reimports, or value overriding
    if (!empty($node->field_os2web_meetings_system_id['und']['0']['value']) && $node->field_os2web_meetings_system_id['und']['0']['value'] != 0) {
	
	
	//updating meetings category
	if (strcmp($node->field_os2web_meetings_category[$node->language][0]['value'], strtolower($xml_data['meeting_category'])) != 0){
	  $node->field_os2web_meetings_category[$node->language][0]['value'] = strtolower($xml_data['meeting_category']);
	}
	
	//updating the color
	if (strcmp($node->field_os2web_meetings_hex[$node->language][0]['value'], strtolower($xml_data['hex_color'])) != 0){
	  $node->field_os2web_meetings_hex[$node->language][0]['value'] = strtolower($xml_data['hex_color']);
	}
	
	//if meeting is to be cancelled, but is not cancelled yet, then cancell it.
	if ($xml_data['cancelled'] == 1 && strcmp($node->field_os2web_meetings_type[$node->language][0]['value'],'Aflyst') != 0){
	    $node->field_os2web_meetings_type['und'][0]['value'] = "Aflyst";	  
	} //if meeting is changed, but is not marked as changed then mark is as changed
	else if ($xml_data['changed'] == 1 && strcmp($node->field_os2web_meetings_type[$node->language][0]['value'],'Planlagt') == 0){
	    $node->field_os2web_meetings_type['und'][0]['value'] = "Ændret";
	}
	
	node_submit($node);
	node_save($node);
	
	return $node;
    }

    $node->title = $xml_data['title'];
    if (!empty($xml_data['title_short'])){
	$node->field_os2web_meetings_abbr[$node->language][0]['value'] = $xml_data['title_short'];
    }     
    else {
        $node->field_os2web_meetings_abbr[$node->language][0]['value'] = $xml_data['title'];
    }

    $node->field_os2web_meetings_sofd_id[$node->language][0]['value'] = $xml_data['meeting_id']; 
    $node->field_os2web_meetings_system_id[$node->language][0]['value'] = '0';
    

    if (!empty($xml_data['meeting_start_date'])) {
        $node->field_os2web_meetings_date[$node->language][0]['value'] = $xml_data['meeting_start_date'];
    }
    
    if (!empty($xml_data['meeting_end_date'])) {
	$node->field_os2web_meetings_date[$node->language][0]['value2'] = $xml_data['meeting_end_date'];
    } else {//to represent that there is no end date
	$node->field_os2web_meetings_date[$node->language][0]['value2'] = $xml_data['meeting_start_date'];
    }
    
    $node->field_os2web_meetings_category[$node->language][0]['value'] = strtolower($xml_data['meeting_category']);
    $node->field_os2web_meetings_hex[$node->language][0]['value'] = strtolower($xml_data['hex_color']);

    $node->field_os2web_meetings_committee[$node->language][0]['tid'] = $tid;
    
    if ($xml_data['cancelled'] == 1){
	$node->field_os2web_meetings_type['und'][0]['value'] = "Aflyst";
    } else if ($xml_data['changed'] == 1){
	$node->field_os2web_meetings_type['und'][0]['value'] = "Ændret";
    }
    else {
	$node->field_os2web_meetings_type['und'][0]['value'] = "Planlagt";
    }
    
    node_submit($node);
    node_save($node);
}

/**
 * Helper function. Marks the meeting as unpublished.
 *
 * @param array $xml_data entry params
 *
 * @return none
 */
function _os2dagsorden_importer_unpublish_meeting($xml_data) {
    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'node')
            ->fieldCondition('field_os2web_meetings_sofd_id', 'value', intval($xml_data['meeting_id']), '=');

    $result = $query->execute();
    if (isset($result['node'])) {
        $nids = array_keys($result['node']);
        $node = reset(entity_load('node', $nids));

        node_unpublish_action($node);
        node_save($node);
    }
}
/**
 * Helper function. Adds the role to the user
 *
 * @param int   $com_tid  committee id
 * @param mixed $user user object
 *
 * @return none
 */
function _os2dagsorden_importer_add_role_to_user($xml_data, $user, $com_tid) {
    $user_role_items = Array();
    $user_role_items = field_get_items('user', $user, 'field_os2web_user_pos');
     $user_has_this_role = FALSE;
     if (is_array($user_role_items)) {
        foreach (@$user_role_items as $item) {
            $currnet_role_item = field_collection_field_get_entity($item);
            if (intval($currnet_role_item->field_os2web_user_pos_id['und'][0]['value']) == intval($xml_data['user_pos_id'])) {
                $user_has_this_role = TRUE;
                $role_item = $currnet_role_item;
                break;
            }
        }
    }
    if (!$user_has_this_role) {
        $role_item = entity_create('field_collection_item', array('field_name' => 'field_os2web_user_pos'));
        $role_item->setHostEntity('user', $user);
    }
    if (!empty($xml_data['member_start_date'])) {
        $role_item->field_os2web_user_pos_valid['und'][0]['value'] = $xml_data['member_start_date'];
    }
    if (!empty($xml_data['member_end_date'])) {
        $role_item->field_os2web_user_pos_valid['und'][0]['value2'] = $xml_data['member_end_date'];
    } 
    if (!empty($com_tid)) {
       $role_item->field_os2web_user_pos_committee['und'][0]['tid'] = $com_tid;
    }
    $role_item->field_os2web_user_pos_name['und'][0]['value'] = $xml_data['role'];
    $role_item->field_os2web_user_pos_priority['und'][0]['value'] = $xml_data['role_priority'];
    $role_item->field_os2web_user_pos_id['und'][0]['value'] = $xml_data['user_pos_id'];

    $role_item->save();
    
     user_save($user);
     
     
    }
