<?php
/**
 * @file
 * os2dagsorden_piwik.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function os2dagsorden_piwik_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance:
  // 'node-os2web_meetings_bullet-field_os2web_meetings_bul_piwik'.
  $field_instances['node-os2web_meetings_bullet-field_os2web_meetings_bul_piwik'] = array(
    'bundle' => 'os2web_meetings_bullet',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'piwik_stats',
        'settings' => array(
          'visibility' => array(
            'bounce_rate' => TRUE,
            'entry_bounce_count' => TRUE,
            'entry_nb_actions' => TRUE,
            'entry_nb_visits' => TRUE,
            'entry_sum_visit_length' => TRUE,
            'exit_nb_visits' => TRUE,
            'exit_rate' => TRUE,
            'nb_hits' => TRUE,
            'nb_visits' => TRUE,
            'sum_time_spent' => TRUE,
          ),
        ),
        'type' => 'piwik_stats_list',
        'weight' => 6,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_os2web_meetings_bul_piwik',
    'label' => 'Piwik',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'piwik_stats',
      'settings' => array(),
      'type' => 'piwik_stats_hidden',
      'weight' => 10,
    ),
  );

  // Exported field_instance:
  // 'node-os2web_meetings_bullet_attach-field_os2web_meetings_bpa_piwik'.
  $field_instances['node-os2web_meetings_bullet_attach-field_os2web_meetings_bpa_piwik'] = array(
    'bundle' => 'os2web_meetings_bullet_attach',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'piwik_stats',
        'settings' => array(
          'visibility' => array(
            'bounce_rate' => TRUE,
            'entry_bounce_count' => TRUE,
            'entry_nb_actions' => TRUE,
            'entry_nb_visits' => TRUE,
            'entry_sum_visit_length' => TRUE,
            'exit_nb_visits' => TRUE,
            'exit_rate' => TRUE,
            'nb_hits' => TRUE,
            'nb_visits' => TRUE,
            'sum_time_spent' => TRUE,
          ),
        ),
        'type' => 'piwik_stats_list',
        'weight' => 8,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_os2web_meetings_bpa_piwik',
    'label' => 'Piwik',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'piwik_stats',
      'settings' => array(),
      'type' => 'piwik_stats_hidden',
      'weight' => 8,
    ),
  );

  // Exported field_instance:
  // 'node-os2web_meetings_meeting-field_os2web_meetings_piwik'.
  $field_instances['node-os2web_meetings_meeting-field_os2web_meetings_piwik'] = array(
    'bundle' => 'os2web_meetings_meeting',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'piwik_stats',
        'settings' => array(
          'visibility' => array(
            'bounce_rate' => TRUE,
            'entry_bounce_count' => TRUE,
            'entry_nb_actions' => TRUE,
            'entry_nb_visits' => TRUE,
            'entry_sum_visit_length' => TRUE,
            'exit_nb_visits' => TRUE,
            'exit_rate' => TRUE,
            'nb_hits' => TRUE,
            'nb_visits' => TRUE,
            'sum_time_spent' => TRUE,
          ),
        ),
        'type' => 'piwik_stats_list',
        'weight' => 33,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_os2web_meetings_piwik',
    'label' => 'Piwik',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'piwik_stats',
      'settings' => array(),
      'type' => 'piwik_stats_hidden',
      'weight' => 23,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Piwik');

  return $field_instances;
}
