<?php

/**
 * OS2Web_Print_Send_to_Friend
 *
 * PHP version 5
 *
 * @category OS2Web
 * @package  OS2Web_Print_Send_to_Friend
 * @author   Stanislav Kutasevits <stan@bellcom.dk>
 * @license  http://www.gnu.org/licenses/gpl-2.0.html GNU General Public License, version 2
 * @link     http://bellcom.dk
 */
module_load_include('inc', 'os2web_print_send_to_friend', '/includes/os2web_print_send_to_friend');
module_load_include('inc', 'os2web_print_send_to_friend', '/handlers/database');

/**
 * Implementation of hook_menu().
 *
 * @return array of links.
 */
function os2web_print_send_to_friend_menu() {
  $items = array();

  $items['meeting/%/bullet-point/%/print'] = array(
    'title' => 'Print Dagsorden Punkt',
    'type' => MENU_CALLBACK,
    'page callback' => 'os2web_print_send_to_friend_print_bullet_point',
    'page arguments' => array(1, 3),
    'access arguments' => array(1, 3),
    'access callback' => 'os2dagsorden_access_helper_check_user_can_see_bullet_point',
  );

  $items['meeting/%/bullet-point/%/send_to_friend_form'] = array(
    'title' => 'Send dagsorden punkt til venner',
    'type' => MENU_CALLBACK,
    'page callback' => 'os2web_print_send_to_friend_send_to_friend_form',
    'page arguments' => array(1, 3),
    'access arguments' => array(1, 3),
    'access callback' => 'os2dagsorden_access_helper_check_user_can_send_bullet_point',
  );

  $items['meeting/%/bullet-point/%/send_to_friend_service'] = array(
    'title' => 'Dagsorden Punkt Send til venner',
    'type' => MENU_CALLBACK,
    'page callback' => 'os2web_print_send_to_friend_send_to_friend',
    'page arguments' => array(1, 3),
    'access arguments' => array(1, 3),
    'access callback' => 'os2dagsorden_access_helper_check_user_can_see_bullet_point',
  );
  $items['meeting/%/print'] = array(
    'title' => 'Print Dagsorden',
    'type' => MENU_CALLBACK,
    'page callback' => 'os2web_print_send_to_friend_print_dagsorden',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
  );
  $items['admin/reports/send_to_friend_log'] = array(
    'title' => 'Send to friend log Report',
    'description' => t('View events that have been logged.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('os2web_print_send_to_friend_log_filter_form'),
    'access arguments' => array('administer os2web'),
    'type' => MENU_NORMAL_ITEM,
  );


  return $items;
}

/**
 * Implements hook_monolog_channel_info().
 */
function os2web_print_send_to_friend_monolog_channel_info() {
  $channels = array();

  $channels['os2web_send_to_friend_channel'] = array(
    'label' => t('Send to friend'),
    'description' => t('Channel for handling bullet point sharing - "Send til ven"'),
    'default profile' => 'os2web_send_to_friend',
  );

  return $channels;
}

/**
 * Implements hook_monolog_handler_info().
 *
 * @return array
 */
function os2web_print_send_to_friend_monolog_handler_info() {
  $handlers = array();

  $handlers['send_to_friend_db'] = array(
    'label' => t('Send to friend (database)'),
    'description' => t('Logs records into send to friend database table'),
    'settings callback' => 'os2web_print_send_to_friend_handler_settings',
    'loader callback' => 'os2web_print_send_to_friend_handler_loader',
  );
  return $handlers;
}

/**
 * Function that logs sending to friend event
 *
 * @param $message
 * @param array $variables
 * @param $severity
 * @param array $context
 */
function os2web_print_send_to_friend_add_to_log($message, $variables = array(), $severity, $context = array()) {
  try {

    // Perform a partial bootstrap if watchdog is called prior to the
    // DRUPAL_BOOTSTRAP_FULL phase.
    if (!function_exists('monolog')) {
      os2dagsorden_logging_bootstrap();
    }
    $logger = monolog('os2web_send_to_friend_channel');
    $message = addslashes(strip_tags(format_string($message, $variables)));
    $level = os2dagsorden_logging_map_severity_level($severity);

    $logger->log($level, $message, $context);
  } catch (Exception $e) {

    // Fail silently since we cannot log any messages or do anything that would
    // trigger another watchdog call.
  }
}

/**
 * Generates the filter form for sent to friend log values
 *
 * @param $form
 * @param $form_state
 * @return array
 */
function os2web_print_send_to_friend_log_filter_form($form, &$form_state) {
  drupal_add_css(drupal_get_path('module', 'os2web_print_send_to_friend') . '/css/os2web_print_send_to_friend.css');
  drupal_add_library('system', 'ui.datepicker');   
  drupal_add_js("(function ($) { $('#date-from').datepicker(); $('#date-to').datepicker();})(jQuery);", 
      array('type' => 'inline', 'scope' => 'footer', 'weight' => 5));
  $form = array();
  $form ['filter-fields'] = array(
    '#type' => 'container',
    '#attributes'=> array(
      'class' => array(
        'filter-fields',
      ),
    )  
  );  
  $form['filter-fields']['user'] = array(
    '#type' => 'textfield',
    '#title' => t('User'),
    '#size' => 60,  
    '#maxlength' => 60,
    '#autocomplete_path' => 'user/autocomplete',
    '#default_value' => $user,
  );
  $form['filter-fields']['text'] = array(
    '#type' => 'textfield',
    '#title' => t('Email'),
    '#size' => 60,
    '#maxlength' => 60,
    '#default_value' => $text,
  );
  $form['filter-fields']['message'] = array(
    '#type' => 'textfield',
    '#title' => t('Message'),
    '#size' => 60,
    '#maxlength' => 60,
    '#default_value' => $message,
  );
   $form ['filter-fields']['date'] = array(
    '#type' => container,
    '#attributes'=> array(
      'class' => array(
        'filter-date-fields',
      ),
    )  
  );
  $form['filter-fields']['date']['from'] = array(
    '#type' => 'textfield',
    '#title' => t('Date'),
    '#attributes' => array('id' => 'date-from'),
    '#size' => 30,
    '#maxlength' => 60,
    '#field_prefix' => t('From'),
    '#default_value' => $from,
   
  );
  $form['filter-fields']['date']['to'] = array(
    '#type' => 'textfield',
    '#size' => 30,
    '#maxlength' => 60,
    '#default_value' => $to,
    '#attributes' => array('id' => 'date-to'),
    '#field_prefix' => t('To'),
  );
  $form ['buttons'] = array(
    '#type' => container,
    '#attributes'=> array(
      'class' => array(
        'filter-buttons',
      ),
    )  
  );
  $form['buttons']['aply'] = array(
    '#type' => 'submit',
    '#value' => t('Filter'),
  );
  $form['buttons']['reset'] = array(
    '#type' => 'submit',
    '#value' => t('Clear'),
    
  );
 if (db_table_exists('os2web_print_send_to_friend_log')) {
  $headers = array(
    array('data' => t('Date'), 'field' => 'time', 'sort' => 'desc'),
    array('data' => t('Message'), 'field' => 'message'),
    array('data' => t('Text'), 'field' => 'text'),
    array('data' => t('User'), 'field' => 'name'));
  $query = db_select('os2web_print_send_to_friend_log', 'l');
  $query->innerJoin('users', 'u', 'l.uid = u.uid');
  $query->fields('l', array('time', 'message', 'text'));
  $query->fields('u', array('name'));
  if (isset($form_state['user']) && !empty($form_state['user'])) {
    $query->condition('u.name', '%' . db_like($form_state['user']) . '%', 'LIKE');
  }

  if (isset($form_state['text']) && !empty($form_state['text'])) {
    $query->condition('l.text', '%' . db_like($form_state['text']) . '%', 'LIKE');
  }
  if (isset($form_state['message']) && !empty($form_state['message'])) {
    $query->condition('l.message', '%' . db_like($form_state['message']) . '%', 'LIKE');
  }
  if (isset($form_state['date']['from']) && isset($form_state['date']['to']) && !empty($form_state['date']['from']) && !empty($form_state['date']['to']))
    $query->condition('l.time', array(strtotime($form_state['date']['from']), strtotime($form_state['date']['to'])), 'BETWEEN');
  elseif (isset($form_state['date']['from']) && !empty($form_state['date']['from']))
    $query->condition('l.time', strtotime($form_state['date']['from']), '>');
  elseif (isset($form_state['date']['to']) && !empty($form_state['date']['to']))
    $query->condition('l.time', strtotime($form_state['date']['to']), '<');

  $query->extend('TableSort') // Add table sort extender.
    ->orderByHeader($headers);
  $pager = $query->extend('PagerDefault')
    ->limit(50);
  $result = $pager->execute()
    ->fetchAllAssoc('time');

  $rows = array();

  foreach ($result as $row) {
    $row->time = date('d-m-Y H:i:s', $row->time);
    $rows[] = array_values((array) $row);
  }

  $form['table'] = array(
    '#theme' => 'table',
    '#header' => $headers,
    '#rows' => $rows,
  );
 }
 else {
   drupal_set_message('There are not log entries yet');
 }
  return $form;
}

/**
 * Clears form values
 *
 * @param $form
 * @param $form_state
 */
function os2web_print_send_to_friend_log_filter_form_submit($form, &$form_state) {
  if ($form_state["values"]["op"] == 'Clear') {
    $form_state['values']['user'] = "";
    $form_state['values']['text'] = "";
    $form_state['values']['message'] = "";
    $form_state['values']['from'] = "";
    $form_state['values']['to'] = "";
  } else {
    $form_state['user'] = $form_state['values']['user'];
    $form_state['text'] = $form_state['values']['text'];
    $form_state['message'] = $form_state['values']['message'];
    $form_state['date']['from'] = $form_state['values']['from'];
    $form_state['date']['to'] = $form_state['values']['to'];
    $form_state['rebuild'] = TRUE;
  }
}

/**
 * Implements hook_requirements().
 */
function os2web_print_send_to_friend_requirements($phase) {
  if ($phase !== 'runtime') {
    return array();
  }
   $t = get_t();
   if (!module_exists('smtp'))
     $requirements['os2web_print_send_to_friend_smtp_module'] = array(
       'title' => $t('OS2Web Print or Send to Friend'),
       'value' => $t('SMTP module'),
       'severity' => REQUIREMENT_ERROR,
       'description' => t('SMTP module is not exists')
     );
   else 
     if (variable_get('smtp_on', '0') == 0)
      $requirements['os2web_print_send_to_friend_smtp_module_active'] = array(
        'title' => $t('OS2Web Print or Send to Friend'),
        'value' => $t('SMTP module'),
        'severity' => REQUIREMENT_ERROR,
        'description' => t('SMTP module is not active')
      );
     else 
      $requirements['os2web_print_send_to_friend_smtp_module_active'] = array(
        'title' => $t('OS2Web Print or Send to Friend'),
        'value' => $t('SMTP module is active'),
        'severity' => REQUIREMENT_OK
      );
  return $requirements;
}