<?php

/**
 * OS2Web_Print_Send_to_Friend
 *
 * PHP version 5
 *
 * @category OS2Web
 * @package  OS2Web_Print_Send_to_Friend
 * @author   Stanislav Kutasevits <stan@bellcom.dk>
 * @license  http://www.gnu.org/licenses/gpl-2.0.html GNU General Public License, version 2
 * @link     http://bellcom.dk
 */

require drupal_get_path('module', 'os2web_print_send_to_friend') . '/includes/os2web_print_send_to_friend.inc';

/**
 * Implementation of hook_menu().
 *
 * @return array of links.
 */
function os2web_print_send_to_friend_menu() {
	$items = array();

	$items['meeting/%/bullet-point/%/print'] = array(
			'title' => 'Print Dagsorden Punkt',
			'type' => MENU_CALLBACK,
			'page callback' => 'os2web_print_send_to_friend_print_bullet_point',
			'page arguments' => array(3),
			'access arguments' => array(1, 3),
			'access callback' => 'os2dagsorden_access_helper_check_user_can_see_bullet_point',
	);

	$items['meeting/%/bullet-point/%/send_to_friend_form'] = array(
			'title' => 'Send dagsorden punkt til venner',
			'type' => MENU_CALLBACK,
			'page callback' => 'os2web_print_send_to_friend_send_to_friend_form',
			'page arguments' => array(1, 3),
			'access arguments' => array(1, 3),
			'access callback' => 'os2dagsorden_access_helper_check_user_can_send_bullet_point',
	);

	$items['meeting/%/bullet-point/%/send_to_friend_service'] = array(
			'title' => 'Dagsorden Punkt Send til venner',
			'type' => MENU_CALLBACK,
			'page callback' => 'os2web_print_send_to_friend_send_to_friend',
			'page arguments' => array(1, 3),
			'access arguments' => array(1, 3),
			'access callback' => 'os2dagsorden_access_helper_check_user_can_see_bullet_point',
	);
	$items['meeting/%/print'] = array(
			'title' => 'Print Dagsorden',
			'type' => MENU_CALLBACK,
			'page callback' => 'os2web_print_send_to_friend_print_dagsorden',
			'page arguments' => array(1),
			'access arguments' => array('access content'),
	);


	return $items;
}

/**
 * Implements hook_monolog_channel_info().
 */
function os2web_print_send_to_friend_monolog_channel_info() {
  $channels = array();

  $channels['os2web_send_to_friend_channel'] = array(
    'label' => t('Send to friend'),
    'description' => t('Channel for handling bullet point sharing - "Send til ven"'),
    'default profile' => 'Send to friend',
  );

  return $channels;
}

function os2web_print_send_to_friend_monolog_handler_info() {
  $handlers = array();

  $handlers['send_to_friend_db'] = array(
    'label' => t('Send to friend (database)'),
    'description' => t('Logs records into send to friend database table'),
    'default settings' => array(
      'filepath' => 'public://monolog/drupal.log',
    ),
    'settings callback' => 'os2web_print_send_to_friend_handler_settings',
    //'loader callback' => 'os2web_print_send_to_friend_handler_loader',
    'handler file' => 'MODULE_PATH/handlers/stream.inc'
    // "handler file" defaults to `MODULE_PATH/handlers/stream.inc` since the
    // hook_monolog_handler_path() returns "handlers".
  );

  return $handlers;
}

function os2web_print_send_to_friend_handler_settings(&$form, &$form_state) {

}

//use Monolog\Handler\ChromePHPHandler;

/**
 * Monolog loader callback; Loads a ChromePHPHandler handler.
 *
 * @return HandlerInterface
 */
function os2web_print_send_to_friend_handler_loader($options){
  return new ChromePHPHandlerr($options['level'], $options['bubble']);
}
