<?php
module_load_include('inc', 'os2dagsorden_content_modify', '/includes/os2dagsorden_content_modify.user');
module_load_include('inc', 'os2dagsorden_content_modify', '/includes/os2dagsorden_content_modify.user.batch');

/**
 * Implementation of hook_menu
 *
 * @return list of links
 */
function os2dagsorden_content_modify_menu() {
  $items = array();

  $items['admin/config/os2dagsorden/create_committee'] = array(
    'title' => 'Committees',
    'description' => 'Module that supports manual creation or editing of the committee',
    'page callback' => '_os2dagsorden_content_modify_committee',
    'access arguments' => array('administer os2web'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/config/os2dagsorden/create_user_position'] = array(
    'title' => 'User positions',
    'description' => 'Module that supports manual creation or editing of the user position',
    'page callback' => '_os2dagsorden_content_modify_user_position',
    'access arguments' => array('administer os2web'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/config/os2dagsorden/attach_user_position'] = array(
    'title' => 'Assign user positions to users',
    'description' => 'Module that supports assigning/removing roles from the users',
    'page callback' => '_os2dagsorden_content_modify_users',
    'access arguments' => array('administer users'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['user/%/simple_edit'] = array(
    'title' => 'User edit simple',
    'page callback' => '_os2dagsorden_content_modify_user_edit_page',
    'page arguments' => array(1),
    'access arguments' => array('administer users'),
    'type' => MENU_LOCAL_TASK,
  );

  $items['user/simple_edit'] = array(
    'title' => 'Mine indstillinger',
    'page callback' => '_os2dagsorden_content_modify_user_edit_page',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'menu-sidepane-menu',
    'options' => array(
      'attributes' => array('id' => 'menu-simple-user-edit'),
    ),
  );

  $items['users-batch-simple-edit/%'] = array(
    'title' => 'Kontoindstillinger',
    'page callback' => '_os2dagsorden_content_modify_user_batch_edit_page',
    'page arguments' => array(1),
    'access arguments' => array('administer users'),
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'menu-sidepane-menu',
    'options' => array(
      'attributes' => array('id' => 'menu-simple-user-edit'),
    ),
  );

  return $items;
}

/**
 * Helper function, redirects to taxonomy creation page.
 *
 * @return none
 */
function _os2dagsorden_content_modify_committee(){
    drupal_goto('admin/structure/taxonomy/os2web_meetings_tax_committee');
}

/**
 * Helper function, redirects to taxonomy user position creation page.
 *
 * @return none
 */
function _os2dagsorden_content_modify_user_position(){
    drupal_goto('admin/structure/taxonomy/user_position');
}

/**
 * Helper function, redirects to taxonomy users edit page.
 *
 * @return none
 */
function _os2dagsorden_content_modify_users(){
    drupal_goto('admin/people');
}

/**
 * Hook to user operations.
 * Adds custom user edit page.
 *
 * @return none
 */
function os2dagsorden_content_modify_user_operations() {
  $operations = array(
    'Add position' => array(
      'label' => t('Add the position to selected user'),
      'callback' => '_os2dagsorden_content_modify_user_edit_redirect',
    ),
  );
  return $operations;
}

/**
 * Redirect for the user edit link from user operation menu.
 * Redirects to simple edit link.
 *
 * @param $accounts array array of the user ids.
 *
 * @return none
 */
function _os2dagsorden_content_modify_user_edit_redirect($accounts){
  $account = array_pop($accounts);
  drupal_goto('user/' . $account . '/simple_edit');
}

/**
 * Calls form for user simple edit.
 * If user has no administer os2web rights, he will be allowed only to edit his own profile.
 *
 * @param $uid int id of the user to modify.
 *
 * @return form
 */
function _os2dagsorden_content_modify_user_edit_page($uid = null){
  $full_user = os2dagsorden_access_helper_get_user();

  if (empty($uid)){
      $uid = $full_user->uid;
  }

  if (!user_access('administer users', $full_user)){
    if ($full_user->uid != $uid){
      drupal_goto('user/simple_edit');
    }
  }
  return drupal_get_form('os2dagsorden_content_modify_user_edit_form', $uid);
}

/**
 * Callback for users batch edit page.
 *
 *
 * @param $uids CSV of the user ID's (uid) that will be affected by this batch process
 *
 * @return form
 */
function _os2dagsorden_content_modify_user_batch_edit_page($uids){
  return drupal_get_form('os2dagsorden_content_modify_user_batch_edit_form', $uids);
}