<?php

/**
 * Implementation of hook_menu
 *
 * @return list of links
 */
function os2dagsorden_content_modify_menu() {
  $items = array();

  $items['admin/config/os2dagsorden/create_committee'] = array(
    'title' => 'Committees',
    'description' => 'Module that supports manual creation or editing of the committee',
    'page callback' => '_os2dagsorden_content_modify_committee',
    'access arguments' => array('administer os2web'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/config/os2dagsorden/create_user_position'] = array(
    'title' => 'User positions',
    'description' => 'Module that supports manual creation or editing of the user position',
    'page callback' => '_os2dagsorden_content_modify_user_position',
    'access arguments' => array('administer os2web'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/config/os2dagsorden/attach_user_position'] = array(
    'title' => 'Assign user positions to users',
    'description' => 'Module that supports assigning/removing roles from the users',
    'page callback' => '_os2dagsorden_content_modify_users',
    'access arguments' => array('administer os2web'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['user/%/simple_edit'] = array(
    'title' => 'User edit simple',
    'page callback' => '_os2dagsorden_content_modify_user_edit_page',
    'page arguments' => array(1),
    'access arguments' => array('administer os2web'),
    'type' => MENU_LOCAL_TASK,
  );

  $items['user/simple_edit'] = array(
    'title' => 'Kontoindstillinger',
    'page callback' => '_os2dagsorden_content_modify_user_edit_page',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'menu-sidepane-menu',
    'options' => array(
      'attributes' => array('id' => 'menu-simple-user-edit'),
    ),
  );

  return $items;
}

/**
 * Helper function, redirects to taxonomy creation page.
 *
 * @return none
 */
function _os2dagsorden_content_modify_committee(){
    drupal_goto('admin/structure/taxonomy/os2web_meetings_tax_committee');
}

/**
 * Helper function, redirects to taxonomy user position creation page.
 *
 * @return none
 */
function _os2dagsorden_content_modify_user_position(){
    drupal_goto('admin/structure/taxonomy/user_position');
}

/**
 * Helper function, redirects to taxonomy users edit page.
 *
 * @return none
 */
function _os2dagsorden_content_modify_users(){
    drupal_goto('admin/people');
}

/**
 * Hook to user operations.
 * Adds custom user edit page.
 *
 * @return none
 */
function os2dagsorden_content_modify_user_operations() {
  $operations = array(
    'Add position' => array(
      'label' => t('Add the position to selected user'),
      'callback' => '_os2dagsorden_content_modify_user_edit_redirect',
    ),
  );
  return $operations;
}

/**
 * Redirect for the user edit link from user operation menu.
 * Redirects to simple edit link.
 *
 * @param $accounts array array of the user ids.
 *
 * @return none
 */
function _os2dagsorden_content_modify_user_edit_redirect($accounts){
  $account = array_pop($accounts);
  drupal_goto('user/' . $account . '/simple_edit');
}

/**
 * Calls form for user simple edit.
 * If user has no administer os2web rights, he will be allowed only to edit his own profile.
 *
 * @param $uid int id of the user to modify.
 *
 * @return form
 */
function _os2dagsorden_content_modify_user_edit_page($uid = null){
  $full_user = os2dagsorden_access_helper_get_user();

  if (empty($uid)){
      $uid = $full_user->uid;
  }

  if (!user_access('administer os2web', $full_user)){
    if ($full_user->uid != $uid){
      drupal_goto('user/simple_edit');
    }
  }
  return drupal_get_form('os2dagsorden_content_modify_user_edit_form', $uid);
}

/**
 * Generates user edit form and (if uid is not null) loads and sets the parameters.
 * Depending on the user rights form is either limited (with no right) of full (with administer os2web right).
 *
 * @param $form       mixed the form
 * @param $form_state mixed the state of the form
 * @param $uid        int   the id of the user to be modified
 *
 * @return form
 */
function os2dagsorden_content_modify_user_edit_form($form, $form_state, $uid){
   
  $form[] = array(
    '#markup' => '<div class="node clearfix">',
  );

  $form['full_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Full name:'),
    '#size' => 60,
    '#maxlength' => 128,
    '#description' => t('Is displayed in the top right corner.'),
  );

  $form['calendar_pref'] = array(
    //'#access' => user_access('administer os2web', $full_user),
    '#type' => 'checkboxes',
    '#options' => array(
      'pol' => t('Political'),
      'org' => t('Organizational')
    ),
    '#title' =>"<b>" . t('Calendar preferences:') . "</b>",
    '#description' => t('Which types of meetings should user see in the calendar'),
  );
  
  $form['user_can_send_closed_bp'] = array(
    '#type' => 'radios',
    '#title' => "<b>" .t('User can send to friend closed bullet points') . "<b>" ,
    '#default_value' => false,
    '#options' => array(
      true => t('Yes'),
      false => t('No')
    ),
  );

  $form['user_roles'] = array(
    '#access' => user_access('administer os2web', $full_user),
    '#type' => 'checkboxes',
    '#options' => array(
      'os2dagsorden limited' => t('OS2Dagsorden limited'),
      'os2dagsorden admin' => t('OS2Dagsorden admin'),
    ),
    '#title' => '<b>' . t('Brugerroller') . '</b>',
    '#description' => t('Hvilke roller tilsættes til brugeren'),
  );

  if (!os2dagsorden_access_helper_is_touch()){
    //render drag and drop functionality
    _os2dagsorden_content_modify_render_drag_and_drop_controls($form, $uid);
  } else {
    //fallback to default controls
    _os2dagsorden_content_modify_render_default_controls($form, $uid);
  }

  //loading common user fields
  if ($uid) {
    _os2dagsorden_conten_modify_load_user_fields($form, $uid);
  }
 
  $form['save_user'] = array(
    '#type' => 'submit',
    '#attributes' => array(
      'class' => array('form-save-submit'),
    ),
    '#value' => t('Save User'),
    '#submit' => array('os2dagsorden_content_modify_user_submit'),
  );
  $form[] = array(
      '#markup' => '</div>',
  );

  $form[] = array(
      '#markup' => '</div>',
  );

  return $form;
}

function _os2dagsorden_content_modify_render_drag_and_drop_controls(&$form, $uid){
  $form[] = array(
    '#markup' => '<div class="form-item"><b>' . t('Træk udvalg fra kassen under Mulige udvalg til Følger-kassen.') . '</b></div>',
  );

  $form[] = array(
    '#markup' => '<div class="select-committee">',
  );
 
  $form['member_of_div'] = array(
    '#access' => user_access('administer os2web'),  
    '#type' => 'item' ,
    '#prefix' => '<label>' . t('Member of:') . '</label>',       
    '#markup' => '',
  ); 
  $form['member_of_hidden'] = array(
    '#type' => 'hidden',       
    '#attributes' => array(   
      'id' => 'member_of_hidden',
    )
  );
  $form['follows_div'] = array(
    '#type' => 'item' ,
    '#prefix' => '<label>' . t('Follows:') . '</label>',       
    '#markup' => '',
  );

  $form['follows_hidden'] = array(
    '#type' => 'hidden',       
    '#attributes' => array(   
      'id' => 'follows_hidden',
    )
  );
  $form['follows_plus_div'] = array(
    '#access' => user_access('administer os2web'),  
    '#type' => 'item' ,
    '#prefix' => '<label>' . t('Follows+:') . '</label>',       
    '#markup' => '',
     
  ); 
  $form['follows_plus_hidden'] = array(
    '#type' => 'hidden',       
    '#attributes' => array(   
      'id' => 'follows_plus_hidden',
    )
  );

  $form['follows_plus_plus_div'] = array(
    '#access' => user_access('administer os2web'),  
    '#type' => 'item' ,
    '#prefix' => '<label>' . t('Follows++:') . '</label>',       
    '#markup' => '',
     
  ); 
  $form['follows_plus_plus_hidden'] = array(
    '#type' => 'hidden',       
    '#attributes' => array(   
      'id' => 'follows_plus_plus_hidden',
    )
  );
  $form[] = array(
   '#markup' => '</div >',//<div class="select-committee">
  );

  $all_user_committee = array();
  if ($uid){
    $user = user_load($uid);

    $com_terms = os2dagsorden_settings_get_active_committees();
    $com_select = array();
    foreach ($com_terms as $com_term) {
      $com_select[$com_term->tid] = $com_term->name;
    }
  
    $content = "<ul id='member_of' class='droptrue'>";
    if (field_get_items('user', $user, 'field_user_committee')) {
      $user_member_of_field = field_get_items('user', $user, 'field_user_committee');
      $selection = array();
      foreach ($user_member_of_field as $member_of) {
	if (isset($com_select[$member_of['tid']])) {
	  $content .= "<li id='{$member_of['tid']}' class='ui-state-default'>{$com_select[$member_of['tid']]}</li>";
	  $selection[] = $member_of['tid'];
	  $all_user_committee[] = $member_of['tid'];          
	} 
      }
      $form['member_of_hidden']['#value'] = implode(',', $selection);
    }
    $form['member_of_div']['#markup'] = $content .'</ul>';
    
    $content = "<ul id='follows' class='droptrue'>";
    if (field_get_items('user', $user, 'field_follows_committee')) {
      $user_follows_field = field_get_items('user', $user, 'field_follows_committee');
      $selection = array();
      
      foreach ($user_follows_field as $follows) {
	if (isset($com_select[$follows['tid']])) {
	  $content .= "<li id='{$follows['tid']}' class='ui-state-default'>{$com_select[$follows['tid']]}</li>";
	  $selection[] = $follows['tid'];
	  $all_user_committee[] = $follows['tid'];          
	} 
      }
      $form['follows_hidden']['#value'] = implode(',', $selection);
    }
    $form['follows_div']['#markup'] = $content .'</ul>';
    
    $content = "<ul id='follows_plus' class='droptrue'>";
    if (field_get_items('user', $user, 'field_follows_committee_plus')) {
      $user_follows_plus_field = field_get_items('user', $user, 'field_follows_committee_plus');
      $selection = array();
  
      foreach ($user_follows_plus_field as $follows_plus) {
	if (isset($com_select[$follows_plus['tid']])) { 
	  $selection[] = $follows_plus['tid'];
	  $content .= "<li id='{$follows_plus['tid']}' class='ui-state-default'>{$com_select[$follows_plus['tid']]}</li>";
	  $all_user_committee[] = $follows_plus['tid'];
	} 
      }
      $form['follows_plus_hidden']['#value'] = implode(',', $selection);
    }
    
    $form['follows_plus_div']['#markup'] = $content .'</ul>';
    
    $content = "<ul id='follows_plus_plus' class='droptrue'>";
    if (field_get_items('user', $user, 'field_follows_committee_pp')) {
      $user_follows_plus_plus_field = field_get_items('user', $user, 'field_follows_committee_pp');
      $selection = array();
      foreach ($user_follows_plus_plus_field as $follows_plus_plus) {
	if (isset($com_select[$follows_plus_plus['tid']])) {  
	  $selection[] = $follows_plus_plus['tid'];
	  $content .= "<li id='{$follows_plus_plus['tid']}' class='ui-state-default'>{$com_select[$follows_plus_plus['tid']]}</li>";
	  $all_user_committee[] = $follows_plus_plus['tid'];
	}
      }
      $form['follows_plus_plus_hidden']['#value'] = implode(',', $selection);
    }
    $form['follows_plus_plus_div']['#markup'] = $content .'</ul>';
  }

  $com_list = "<ul id='available_committee' class='droptrue'>"; 
  foreach ($com_select as $tid=>$com_term) {
    if (!in_array($tid, $all_user_committee))
    $com_list  .= "<li id='{$tid}' class='ui-state-default'>{$com_term}</li>"; 
  }
  $com_list .= "</ul>";
  $form['available_committee'] = array(
    '#type' => 'item' ,
    '#prefix' => "<div class='available_committee'><label>" . t('Available committee') . ":</label>",       
    '#markup' => $com_list,
    '#suffix' => '</div>'
  ); 
  $form[] = array(
    '#markup' => "<div style='clear:both'>",
  );
}

function _os2dagsorden_content_modify_render_default_controls(&$form, $uid){
  $com_terms = os2dagsorden_settings_get_active_committees();
  $com_select = array();

  foreach ($com_terms as $com_term) {
    $com_select[$com_term->tid] = $com_term->name;
  }

  $form['member_of'] = array(
      '#access' => user_access('administer os2web'),
      '#type' => 'select',
      '#title' => t('Member of:'),
      '#options' => $com_select,
      '#multiple' => TRUE,
      '#size' => 10,
      //'#description' => t('For multiple selection hold <b>CTRL</b>.<br/>
      //The committees user is member of are presented in the right side pane.'),
  );
    

  $form['follows'] = array(
      '#type' => 'select',
      '#title' => t('Follows:'),
      '#options' => $com_select,
      '#multiple' => TRUE,
      '#size' => 10,
      //'#description' => t('For multiple selection hold <b>CTRL</b>.<br/>
      //The committees user follows are presented in the right side pane.'),
  );
  
  $form['follows_plus'] = array(
      '#access' => user_access('administer os2web'),
      '#type' => 'select',
      '#title' => t('Follows+:'),
      '#options' => $com_select,
      '#multiple' => TRUE,
      '#size' => 10,
      //'#description' => t('For multiple selection hold <b>CTRL</b>.<br/>
      //The committees user follows+ are presented in the right side pane.'),
  );
    
  $form['follows_plus_plus'] = array(
      '#access' => user_access('administer os2web'),
      '#type' => 'select',
      '#title' => t('Follows++:'),
      '#options' => $com_select,
      '#multiple' => TRUE,
      '#size' => 10,
      //'#description' => t('For multiple selection hold <b>CTRL</b>.<br/>
      //The committees user follows+ are presented in the right side pane.'),
  );

  if ($uid){
    $user = user_load($uid);

    if (field_get_items('user', $user, 'field_user_committee')){
      $user_member_of_field = field_get_items('user', $user, 'field_user_committee');
      $selection = array();
      foreach ($user_member_of_field as $member_of){
	$selection[] = $member_of['tid'];
      }
      $form['member_of']['#default_value'] = $selection;
    }
  
    if (field_get_items('user', $user, 'field_follows_committee')){
      $user_follows_field = field_get_items('user', $user, 'field_follows_committee');
      $selection = array();
      foreach ($user_follows_field as $follows){
	$selection[] = $follows['tid'];
      }
      $form['follows']['#default_value'] = $selection;
    }
  
    if (field_get_items('user', $user, 'field_follows_committee_plus')){
      $user_follows_plus_field = field_get_items('user', $user, 'field_follows_committee_plus');
      $selection = array();
      foreach ($user_follows_plus_field as $follows_plus){
	$selection[] = $follows_plus['tid'];
      }
      $form['follows_plus']['#default_value'] = $selection;
    }
    if (field_get_items('user', $user, 'field_follows_committee_pp')){
      $user_follows_plus_field = field_get_items('user', $user, 'field_follows_committee_pp');
      $selection = array();
      foreach ($user_follows_plus_field as $follows_plus){
	$selection[] = $follows_plus['tid'];
      }
      $form['follows_plus_plus']['#default_value'] = $selection;
    }
  }
}

function _os2dagsorden_conten_modify_load_user_fields(&$form, $uid){
    //saving for usage in the submit function
    $form['uid'] = array(
      '#type' => 'value',
      '#value' => $uid,
    );
    $user = user_load($uid);

    //filling the fields
    if (field_get_items('user', $user, 'field_user_full_name') ){
      $full_name_field = array_pop(field_get_items('user', $user, 'field_user_full_name'));
      $form['full_name']['#default_value'] = $full_name_field['value'];
    }

    if (field_get_items('user', $user, 'field_user_can_send_closed_bp')){
      $user_can_send_closed_bp = array_pop(field_get_items('user', $user, 'field_user_can_send_closed_bp'));
      $form['user_can_send_closed_bp']['#default_value'] = $user_can_send_closed_bp['value'];
    }
    
    if (field_get_items('user', $user, 'field_user_meetings_category')) {
      $calendar_prefs_field = field_get_items('user', $user, 'field_user_meetings_category');
      $selection = array();
      foreach ($calendar_prefs_field as $cal_pref) {
	$selection[] = $cal_pref[value];
      }
      $form['calendar_pref']['#default_value'] = $selection;
    }

    $form['user_roles']['#default_value'] = $user->roles;
}

/**
 * Submit for user edit form. Updates user profile.
 *
 * @param $form       mixed the form
 * @param $form_state mixed state of the form
 *
 * @return none
 */
function os2dagsorden_content_modify_user_submit($form, $form_state){
  $input = $form_state['input'];

  //input extraction
  extract($input);
  if (!os2dagsorden_access_helper_is_touch()){
    $follows = explode(',', $follows_hidden);
    $member_of = explode(',', $member_of_hidden);
    $follows_plus = explode(',', $follows_plus_hidden);
    $follows_plus_plus = explode(',', $follows_plus_plus_hidden);
  }

  $user = user_load($form_state['values']['uid']);
  $user->field_user_full_name['und'][0]['value'] = $full_name;
  $user->field_user_can_send_closed_bp['und'][0]['value'] = $user_can_send_closed_bp;
         
  //unsetting follows committees
  $user->field_follows_committee['und'] = array();
  if ($follows){
    foreach ($follows as $tid){  
    if (!empty($tid))       
     $user->field_follows_committee['und'][]['tid'] = $tid;
    }
  }

  //unsetting calendar preferences
  $user->field_user_meetings_category['und'] = array();
  foreach ($calendar_pref as $cal_pref){
    $user->field_user_meetings_category['und'][]['value'] = $cal_pref;
  }

  if (user_access('administer os2web')){//only for the full form submit
    //unsetting positions
    $user->field_user_positions['und'] = array();
    if ($user_pos){
      foreach ($user_pos as $tid){
	$user->field_user_positions['und'][]['tid'] = $tid;
      }
    }

    //unsetting committees
    $user->field_user_committee['und'] = array();
    if ($member_of){
        
      foreach ($member_of as $tid){
        if (!empty($tid))      
	$user->field_user_committee['und'][]['tid'] = $tid;
      }
    }

    //unsetting follows plus committees
    $user->field_follows_committee_plus['und'] = array();
    if ($follows_plus){
      foreach ($follows_plus as $tid){
       if (!empty($tid))   
	 $user->field_follows_committee_plus['und'][]['tid'] = $tid;
      }
    }
    
    //unsetting follows ++ committees
    $user->field_follows_committee_pp['und'] = array();
    if ($follows_plus_plus){
      foreach ($follows_plus_plus as $tid){
        if (!empty($tid))      
	 $user->field_follows_committee_pp['und'][]['tid'] = $tid;
      }
    }

    //os2dagsorden limited role
    $user_roles_saved = $user->roles;

    //os2dagsorden admin role
    if (!$user_roles['os2dagsorden admin']){
      if (($key = array_search('os2dagsorden admin', $user_roles_saved)) !== false) {
	  unset($user_roles_saved[$key]);
      }
    } else {
      if ((array_search('os2dagsorden admin', $user_roles_saved)) === false) {
	  $rid = user_role_load_by_name('os2dagsorden admin')->rid;
	  $user_roles_saved[$rid] = 'os2dagsorden admin';
      }
    }

    if (!$user_roles['os2dagsorden limited']){
      if (($key = array_search('os2dagsorden limited', $user_roles_saved)) !== false) {
	  unset($user_roles_saved[$key]);
      }
    } else {
      if ((array_search('os2dagsorden limited', $user_roles_saved)) === false) {
	  $rid = user_role_load_by_name('os2dagsorden limited')->rid;
	  $user_roles_saved[$rid] = 'os2dagsorden limited';
      }
    }
    $user->roles = $user_roles_saved;
  }

  user_save($user);
  drupal_set_message(t('Dine ændringer er blevet gemt'));
}
