<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname(dirname($vendorDir))).'/default/files/composer';

return array(
    'Psr\\Log\\' => array($vendorDir . '/psr/log'),
    'Drupal\\Monolog' => array($baseDir . '/../../../all/modules/monolog/src'),
);
