<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname(dirname($vendorDir))).'/default/files/composer';

return array(
    'Drupal\\Monolog' => array($baseDir . '/../../../../profiles/os2dagsorden/modules/contrib/monolog/src'),
);
